package org.vamdc.kida.dao.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _AstrophysicianExport was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _AstrophysicianExport extends CayenneDataObject {

    public static final String ACCEPTED_SPECIES_PROPERTY = "acceptedSpecies";
    public static final String CREATED_AT_PROPERTY = "createdAt";
    public static final String DENIED_SPECIES_PROPERTY = "deniedSpecies";
    public static final String EXCLUDED_ELEMENTS_PROPERTY = "excludedElements";
    public static final String EXPORT_TYPE_PROPERTY = "exportType";
    public static final String FILENAME_REACTIONS_PROPERTY = "filenameReactions";
    public static final String FILENAME_SPECIES_PROPERTY = "filenameSpecies";
    public static final String ID_PROPERTY = "id";
    public static final String INPUT_ELEMENTS_PROPERTY = "inputElements";
    public static final String INPUT_SPECIES_PROPERTY = "inputSpecies";
    public static final String IS_THREE_BODY_PROPERTY = "isThreeBody";
    public static final String PMAX_PROPERTY = "pmax";
    public static final String PMIN_PROPERTY = "pmin";
    public static final String REAC_PROD_PROPERTY = "reacProd";
    public static final String TMAX_PROPERTY = "tmax";
    public static final String TMIN_PROPERTY = "tmin";
    public static final String TYPE_PROPERTY = "type";
    public static final String TYPE_REACTION_PROPERTY = "typeReaction";
    public static final String UPDATED_AT_PROPERTY = "updatedAt";
    public static final String USER_EMAIL_PROPERTY = "userEmail";

    public static final String ID_PK_COLUMN = "id";

    public void setAcceptedSpecies(String acceptedSpecies) {
        writeProperty("acceptedSpecies", acceptedSpecies);
    }
    public String getAcceptedSpecies() {
        return (String)readProperty("acceptedSpecies");
    }

    public void setCreatedAt(Date createdAt) {
        writeProperty("createdAt", createdAt);
    }
    public Date getCreatedAt() {
        return (Date)readProperty("createdAt");
    }

    public void setDeniedSpecies(String deniedSpecies) {
        writeProperty("deniedSpecies", deniedSpecies);
    }
    public String getDeniedSpecies() {
        return (String)readProperty("deniedSpecies");
    }

    public void setExcludedElements(String excludedElements) {
        writeProperty("excludedElements", excludedElements);
    }
    public String getExcludedElements() {
        return (String)readProperty("excludedElements");
    }

    public void setExportType(String exportType) {
        writeProperty("exportType", exportType);
    }
    public String getExportType() {
        return (String)readProperty("exportType");
    }

    public void setFilenameReactions(String filenameReactions) {
        writeProperty("filenameReactions", filenameReactions);
    }
    public String getFilenameReactions() {
        return (String)readProperty("filenameReactions");
    }

    public void setFilenameSpecies(String filenameSpecies) {
        writeProperty("filenameSpecies", filenameSpecies);
    }
    public String getFilenameSpecies() {
        return (String)readProperty("filenameSpecies");
    }

    public void setId(Integer id) {
        writeProperty("id", id);
    }
    public Integer getId() {
        return (Integer)readProperty("id");
    }

    public void setInputElements(String inputElements) {
        writeProperty("inputElements", inputElements);
    }
    public String getInputElements() {
        return (String)readProperty("inputElements");
    }

    public void setInputSpecies(String inputSpecies) {
        writeProperty("inputSpecies", inputSpecies);
    }
    public String getInputSpecies() {
        return (String)readProperty("inputSpecies");
    }

    public void setIsThreeBody(Long isThreeBody) {
        writeProperty("isThreeBody", isThreeBody);
    }
    public Long getIsThreeBody() {
        return (Long)readProperty("isThreeBody");
    }

    public void setPmax(Integer pmax) {
        writeProperty("pmax", pmax);
    }
    public Integer getPmax() {
        return (Integer)readProperty("pmax");
    }

    public void setPmin(Integer pmin) {
        writeProperty("pmin", pmin);
    }
    public Integer getPmin() {
        return (Integer)readProperty("pmin");
    }

    public void setReacProd(String reacProd) {
        writeProperty("reacProd", reacProd);
    }
    public String getReacProd() {
        return (String)readProperty("reacProd");
    }

    public void setTmax(Integer tmax) {
        writeProperty("tmax", tmax);
    }
    public Integer getTmax() {
        return (Integer)readProperty("tmax");
    }

    public void setTmin(Integer tmin) {
        writeProperty("tmin", tmin);
    }
    public Integer getTmin() {
        return (Integer)readProperty("tmin");
    }

    public void setType(String type) {
        writeProperty("type", type);
    }
    public String getType() {
        return (String)readProperty("type");
    }

    public void setTypeReaction(String typeReaction) {
        writeProperty("typeReaction", typeReaction);
    }
    public String getTypeReaction() {
        return (String)readProperty("typeReaction");
    }

    public void setUpdatedAt(Date updatedAt) {
        writeProperty("updatedAt", updatedAt);
    }
    public Date getUpdatedAt() {
        return (Date)readProperty("updatedAt");
    }

    public void setUserEmail(String userEmail) {
        writeProperty("userEmail", userEmail);
    }
    public String getUserEmail() {
        return (String)readProperty("userEmail");
    }

}
