package org.vamdc.kida.dao.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.vamdc.kida.dao.BiblioBook;
import org.vamdc.kida.dao.BiblioJournal;
import org.vamdc.kida.dao.BiblioThesis;
import org.vamdc.kida.dao.ChannelValue;
import org.vamdc.kida.dao.K0Value;

/**
 * Class _Biblio was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Biblio extends CayenneDataObject {

    public static final String AUTHORS_PROPERTY = "authors";
    public static final String CREATED_AT_PROPERTY = "createdAt";
    public static final String ENTITY_TYPE_PROPERTY = "entityType";
    public static final String ID_PROPERTY = "id";
    public static final String IS_CHECKED_PROPERTY = "isChecked";
    public static final String MAIN_AUTHOR_PROPERTY = "mainAuthor";
    public static final String TITLE_PROPERTY = "title";
    public static final String UPDATED_AT_PROPERTY = "updatedAt";
    public static final String YEAR_PROPERTY = "year";
    public static final String BIBLIOGRAPHY_PROPERTY = "bibliography";
    public static final String BIBLIOGRAPHY1_PROPERTY = "bibliography1";
    public static final String BIBLIOGRAPHY2_PROPERTY = "bibliography2";
    public static final String CHANNEL_VALUES_PROPERTY = "channelValues";
    public static final String K0VALUES_PROPERTY = "k0Values";

    public static final String ID_PK_COLUMN = "id";

    public void setAuthors(String authors) {
        writeProperty("authors", authors);
    }
    public String getAuthors() {
        return (String)readProperty("authors");
    }

    public void setCreatedAt(Date createdAt) {
        writeProperty("createdAt", createdAt);
    }
    public Date getCreatedAt() {
        return (Date)readProperty("createdAt");
    }

    public void setEntityType(String entityType) {
        writeProperty("entityType", entityType);
    }
    public String getEntityType() {
        return (String)readProperty("entityType");
    }

    public void setId(Integer id) {
        writeProperty("id", id);
    }
    public Integer getId() {
        return (Integer)readProperty("id");
    }

    public void setIsChecked(Long isChecked) {
        writeProperty("isChecked", isChecked);
    }
    public Long getIsChecked() {
        return (Long)readProperty("isChecked");
    }

    public void setMainAuthor(String mainAuthor) {
        writeProperty("mainAuthor", mainAuthor);
    }
    public String getMainAuthor() {
        return (String)readProperty("mainAuthor");
    }

    public void setTitle(String title) {
        writeProperty("title", title);
    }
    public String getTitle() {
        return (String)readProperty("title");
    }

    public void setUpdatedAt(Date updatedAt) {
        writeProperty("updatedAt", updatedAt);
    }
    public Date getUpdatedAt() {
        return (Date)readProperty("updatedAt");
    }

    public void setYear(Integer year) {
        writeProperty("year", year);
    }
    public Integer getYear() {
        return (Integer)readProperty("year");
    }

    public void setBibliography(BiblioBook bibliography) {
        setToOneTarget("bibliography", bibliography, true);
    }

    public BiblioBook getBibliography() {
        return (BiblioBook)readProperty("bibliography");
    }


    public void setBibliography1(BiblioJournal bibliography1) {
        setToOneTarget("bibliography1", bibliography1, true);
    }

    public BiblioJournal getBibliography1() {
        return (BiblioJournal)readProperty("bibliography1");
    }


    public void setBibliography2(BiblioThesis bibliography2) {
        setToOneTarget("bibliography2", bibliography2, true);
    }

    public BiblioThesis getBibliography2() {
        return (BiblioThesis)readProperty("bibliography2");
    }


    public void addToChannelValues(ChannelValue obj) {
        addToManyTarget("channelValues", obj, true);
    }
    public void removeFromChannelValues(ChannelValue obj) {
        removeToManyTarget("channelValues", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<ChannelValue> getChannelValues() {
        return (List<ChannelValue>)readProperty("channelValues");
    }


    public void addToK0Values(K0Value obj) {
        addToManyTarget("k0Values", obj, true);
    }
    public void removeFromK0Values(K0Value obj) {
        removeToManyTarget("k0Values", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<K0Value> getK0Values() {
        return (List<K0Value>)readProperty("k0Values");
    }


}
