package org.vamdc.kida.dao.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.vamdc.kida.dao.Biblio;

/**
 * Class _BiblioJournal was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _BiblioJournal extends CayenneDataObject {

    public static final String BIBLIOGRAPHY_ID_PROPERTY = "bibliographyId";
    public static final String CREATED_AT_PROPERTY = "createdAt";
    public static final String DOI_PROPERTY = "doi";
    public static final String JOURNAL_PROPERTY = "journal";
    public static final String PAGE_PROPERTY = "page";
    public static final String UPDATED_AT_PROPERTY = "updatedAt";
    public static final String BIBLIOGRAPHY_PROPERTY = "bibliography";

    public static final String BIBLIOGRAPHY_ID_PK_COLUMN = "bibliography_id";

    public void setBibliographyId(Integer bibliographyId) {
        writeProperty("bibliographyId", bibliographyId);
    }
    public Integer getBibliographyId() {
        return (Integer)readProperty("bibliographyId");
    }

    public void setCreatedAt(Date createdAt) {
        writeProperty("createdAt", createdAt);
    }
    public Date getCreatedAt() {
        return (Date)readProperty("createdAt");
    }

    public void setDoi(String doi) {
        writeProperty("doi", doi);
    }
    public String getDoi() {
        return (String)readProperty("doi");
    }

    public void setJournal(String journal) {
        writeProperty("journal", journal);
    }
    public String getJournal() {
        return (String)readProperty("journal");
    }

    public void setPage(String page) {
        writeProperty("page", page);
    }
    public String getPage() {
        return (String)readProperty("page");
    }

    public void setUpdatedAt(Date updatedAt) {
        writeProperty("updatedAt", updatedAt);
    }
    public Date getUpdatedAt() {
        return (Date)readProperty("updatedAt");
    }

    public void setBibliography(Biblio bibliography) {
        setToOneTarget("bibliography", bibliography, true);
    }

    public Biblio getBibliography() {
        return (Biblio)readProperty("bibliography");
    }


}
