package org.vamdc.kida.dao.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.vamdc.kida.dao.BugState;
import org.vamdc.kida.dao.SfGuardUser;

/**
 * Class _BugsAndFeatures was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _BugsAndFeatures extends CayenneDataObject {

    public static final String CREATED_AT_PROPERTY = "createdAt";
    public static final String DESCRIPTION_PROPERTY = "description";
    public static final String ID_PROPERTY = "id";
    public static final String PAGE_PROPERTY = "page";
    public static final String PRIORITY_ID_PROPERTY = "priorityId";
    public static final String TYPE_BUG_PROPERTY = "typeBug";
    public static final String UPDATED_AT_PROPERTY = "updatedAt";
    public static final String STATE_PROPERTY = "state";
    public static final String TO_SF_GUARD_USER_PROPERTY = "toSfGuardUser";

    public static final String ID_PK_COLUMN = "id";

    public void setCreatedAt(Date createdAt) {
        writeProperty("createdAt", createdAt);
    }
    public Date getCreatedAt() {
        return (Date)readProperty("createdAt");
    }

    public void setDescription(String description) {
        writeProperty("description", description);
    }
    public String getDescription() {
        return (String)readProperty("description");
    }

    public void setId(Integer id) {
        writeProperty("id", id);
    }
    public Integer getId() {
        return (Integer)readProperty("id");
    }

    public void setPage(String page) {
        writeProperty("page", page);
    }
    public String getPage() {
        return (String)readProperty("page");
    }

    public void setPriorityId(Integer priorityId) {
        writeProperty("priorityId", priorityId);
    }
    public Integer getPriorityId() {
        return (Integer)readProperty("priorityId");
    }

    public void setTypeBug(String typeBug) {
        writeProperty("typeBug", typeBug);
    }
    public String getTypeBug() {
        return (String)readProperty("typeBug");
    }

    public void setUpdatedAt(Date updatedAt) {
        writeProperty("updatedAt", updatedAt);
    }
    public Date getUpdatedAt() {
        return (Date)readProperty("updatedAt");
    }

    public void setState(BugState state) {
        setToOneTarget("state", state, true);
    }

    public BugState getState() {
        return (BugState)readProperty("state");
    }


    public void setToSfGuardUser(SfGuardUser toSfGuardUser) {
        setToOneTarget("toSfGuardUser", toSfGuardUser, true);
    }

    public SfGuardUser getToSfGuardUser() {
        return (SfGuardUser)readProperty("toSfGuardUser");
    }


}
