package org.vamdc.kida.dao.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.vamdc.kida.dao.Channel;
import org.vamdc.kida.dao.Specie;

/**
 * Class _ChannelHasSpecie was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ChannelHasSpecie extends CayenneDataObject {

    public static final String CHANNEL_ID_PROPERTY = "channelId";
    public static final String CREATED_AT_PROPERTY = "createdAt";
    public static final String OCCURRENCE_PROPERTY = "occurrence";
    public static final String SPECIE_ID_PROPERTY = "specieId";
    public static final String TYPE_PROPERTY = "type";
    public static final String UPDATED_AT_PROPERTY = "updatedAt";
    public static final String CHANNEL_PROPERTY = "channel";
    public static final String SPECIE_PROPERTY = "specie";

    public static final String CHANNEL_ID_PK_COLUMN = "channel_id";
    public static final String SPECIE_ID_PK_COLUMN = "specie_id";
    public static final String TYPE_PK_COLUMN = "type";

    public void setChannelId(Integer channelId) {
        writeProperty("channelId", channelId);
    }
    public Integer getChannelId() {
        return (Integer)readProperty("channelId");
    }

    public void setCreatedAt(Date createdAt) {
        writeProperty("createdAt", createdAt);
    }
    public Date getCreatedAt() {
        return (Date)readProperty("createdAt");
    }

    public void setOccurrence(Integer occurrence) {
        writeProperty("occurrence", occurrence);
    }
    public Integer getOccurrence() {
        return (Integer)readProperty("occurrence");
    }

    public void setSpecieId(Integer specieId) {
        writeProperty("specieId", specieId);
    }
    public Integer getSpecieId() {
        return (Integer)readProperty("specieId");
    }

    public void setType(String type) {
        writeProperty("type", type);
    }
    public String getType() {
        return (String)readProperty("type");
    }

    public void setUpdatedAt(Date updatedAt) {
        writeProperty("updatedAt", updatedAt);
    }
    public Date getUpdatedAt() {
        return (Date)readProperty("updatedAt");
    }

    public void setChannel(Channel channel) {
        setToOneTarget("channel", channel, true);
    }

    public Channel getChannel() {
        return (Channel)readProperty("channel");
    }


    public void setSpecie(Specie specie) {
        setToOneTarget("specie", specie, true);
    }

    public Specie getSpecie() {
        return (Specie)readProperty("specie");
    }


}
