package org.vamdc.kida.dao.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.vamdc.kida.dao.Bibliography;
import org.vamdc.kida.dao.ChannelValue;
import org.vamdc.kida.dao.TotalRate;
import org.vamdc.kida.dao.VariableName;

/**
 * Class _ChannelVariable was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ChannelVariable extends CayenneDataObject {

    public static final String COMMENT_PROPERTY = "comment";
    public static final String CREATED_AT_PROPERTY = "createdAt";
    public static final String EXPOSANT_PROPERTY = "exposant";
    public static final String ID_PROPERTY = "id";
    public static final String REF_PROPERTY = "ref";
    public static final String TYPE_UNCERT_PROPERTY = "typeUncert";
    public static final String UNCERT_PROPERTY = "uncert";
    public static final String UPDATED_AT_PROPERTY = "updatedAt";
    public static final String VALUE_PROPERTY = "value";
    public static final String BIBLIOGRAPHY_PROPERTY = "bibliography";
    public static final String CHANNEL_VALUE_PROPERTY = "channelValue";
    public static final String TOTAL_RATE_PROPERTY = "totalRate";
    public static final String VARIABLE_NAME_PROPERTY = "variableName";

    public static final String ID_PK_COLUMN = "id";

    public void setComment(String comment) {
        writeProperty("comment", comment);
    }
    public String getComment() {
        return (String)readProperty("comment");
    }

    public void setCreatedAt(Date createdAt) {
        writeProperty("createdAt", createdAt);
    }
    public Date getCreatedAt() {
        return (Date)readProperty("createdAt");
    }

    public void setExposant(Integer exposant) {
        writeProperty("exposant", exposant);
    }
    public Integer getExposant() {
        return (Integer)readProperty("exposant");
    }

    public void setId(Integer id) {
        writeProperty("id", id);
    }
    public Integer getId() {
        return (Integer)readProperty("id");
    }

    public void setRef(String ref) {
        writeProperty("ref", ref);
    }
    public String getRef() {
        return (String)readProperty("ref");
    }

    public void setTypeUncert(String typeUncert) {
        writeProperty("typeUncert", typeUncert);
    }
    public String getTypeUncert() {
        return (String)readProperty("typeUncert");
    }

    public void setUncert(String uncert) {
        writeProperty("uncert", uncert);
    }
    public String getUncert() {
        return (String)readProperty("uncert");
    }

    public void setUpdatedAt(Date updatedAt) {
        writeProperty("updatedAt", updatedAt);
    }
    public Date getUpdatedAt() {
        return (Date)readProperty("updatedAt");
    }

    public void setValue(Float value) {
        writeProperty("value", value);
    }
    public Float getValue() {
        return (Float)readProperty("value");
    }

    public void setBibliography(Bibliography bibliography) {
        setToOneTarget("bibliography", bibliography, true);
    }

    public Bibliography getBibliography() {
        return (Bibliography)readProperty("bibliography");
    }


    public void setChannelValue(ChannelValue channelValue) {
        setToOneTarget("channelValue", channelValue, true);
    }

    public ChannelValue getChannelValue() {
        return (ChannelValue)readProperty("channelValue");
    }


    public void setTotalRate(TotalRate totalRate) {
        setToOneTarget("totalRate", totalRate, true);
    }

    public TotalRate getTotalRate() {
        return (TotalRate)readProperty("totalRate");
    }


    public void setVariableName(VariableName variableName) {
        setToOneTarget("variableName", variableName, true);
    }

    public VariableName getVariableName() {
        return (VariableName)readProperty("variableName");
    }


}
