package org.vamdc.kida.dao.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.vamdc.kida.dao.ChannelHasSpecie;
import org.vamdc.kida.dao.ChannelValue;
import org.vamdc.kida.dao.ExperimentHasChannel;
import org.vamdc.kida.dao.Specie;
import org.vamdc.kida.dao.TypeChannel;

/**
 * Class _Channel was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Channel extends CayenneDataObject {

    public static final String ADDED_STATUS_PROPERTY = "addedStatus";
    public static final String CREATED_AT_PROPERTY = "createdAt";
    public static final String ID_PROPERTY = "id";
    public static final String NUM_PROPERTY = "num";
    public static final String STATUS_PROPERTY = "status";
    public static final String UPDATED_AT_PROPERTY = "updatedAt";
    public static final String CHANNEL_HAS_SPECIES_PROPERTY = "channelHasSpecies";
    public static final String CHANNEL_VALUES_PROPERTY = "channelValues";
    public static final String EXPERIMENT_HAS_CHANNELS_PROPERTY = "experimentHasChannels";
    public static final String SPECIES_PROPERTY = "species";
    public static final String TYPE_CHANNEL_PROPERTY = "typeChannel";

    public static final String ID_PK_COLUMN = "id";

    public void setAddedStatus(Integer addedStatus) {
        writeProperty("addedStatus", addedStatus);
    }
    public Integer getAddedStatus() {
        return (Integer)readProperty("addedStatus");
    }

    public void setCreatedAt(Date createdAt) {
        writeProperty("createdAt", createdAt);
    }
    public Date getCreatedAt() {
        return (Date)readProperty("createdAt");
    }

    public void setId(Integer id) {
        writeProperty("id", id);
    }
    public Integer getId() {
        return (Integer)readProperty("id");
    }

    public void setNum(Integer num) {
        writeProperty("num", num);
    }
    public Integer getNum() {
        return (Integer)readProperty("num");
    }

    public void setStatus(String status) {
        writeProperty("status", status);
    }
    public String getStatus() {
        return (String)readProperty("status");
    }

    public void setUpdatedAt(Date updatedAt) {
        writeProperty("updatedAt", updatedAt);
    }
    public Date getUpdatedAt() {
        return (Date)readProperty("updatedAt");
    }

    public void addToChannelHasSpecies(ChannelHasSpecie obj) {
        addToManyTarget("channelHasSpecies", obj, true);
    }
    public void removeFromChannelHasSpecies(ChannelHasSpecie obj) {
        removeToManyTarget("channelHasSpecies", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<ChannelHasSpecie> getChannelHasSpecies() {
        return (List<ChannelHasSpecie>)readProperty("channelHasSpecies");
    }


    public void addToChannelValues(ChannelValue obj) {
        addToManyTarget("channelValues", obj, true);
    }
    public void removeFromChannelValues(ChannelValue obj) {
        removeToManyTarget("channelValues", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<ChannelValue> getChannelValues() {
        return (List<ChannelValue>)readProperty("channelValues");
    }


    public void addToExperimentHasChannels(ExperimentHasChannel obj) {
        addToManyTarget("experimentHasChannels", obj, true);
    }
    public void removeFromExperimentHasChannels(ExperimentHasChannel obj) {
        removeToManyTarget("experimentHasChannels", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<ExperimentHasChannel> getExperimentHasChannels() {
        return (List<ExperimentHasChannel>)readProperty("experimentHasChannels");
    }


    public void addToSpecies(Specie obj) {
        addToManyTarget("species", obj, true);
    }
    public void removeFromSpecies(Specie obj) {
        removeToManyTarget("species", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Specie> getSpecies() {
        return (List<Specie>)readProperty("species");
    }


    public void setTypeChannel(TypeChannel typeChannel) {
        setToOneTarget("typeChannel", typeChannel, true);
    }

    public TypeChannel getTypeChannel() {
        return (TypeChannel)readProperty("typeChannel");
    }


}
