package org.vamdc.kida.dao.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.vamdc.kida.dao.SfGuardUser;

/**
 * Class _Comment was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Comment extends CayenneDataObject {

    public static final String COMMENT_TEXT_PROPERTY = "commentText";
    public static final String CREATED_AT_PROPERTY = "createdAt";
    public static final String ENTITY_ID_PROPERTY = "entityId";
    public static final String ENTITY_TYPE_PROPERTY = "entityType";
    public static final String ID_PROPERTY = "id";
    public static final String ID_PERE_PROPERTY = "idPere";
    public static final String UPDATED_AT_PROPERTY = "updatedAt";
    public static final String TO_SF_GUARD_USER_PROPERTY = "toSfGuardUser";

    public static final String ID_PK_COLUMN = "id";

    public void setCommentText(String commentText) {
        writeProperty("commentText", commentText);
    }
    public String getCommentText() {
        return (String)readProperty("commentText");
    }

    public void setCreatedAt(Date createdAt) {
        writeProperty("createdAt", createdAt);
    }
    public Date getCreatedAt() {
        return (Date)readProperty("createdAt");
    }

    public void setEntityId(Integer entityId) {
        writeProperty("entityId", entityId);
    }
    public Integer getEntityId() {
        return (Integer)readProperty("entityId");
    }

    public void setEntityType(String entityType) {
        writeProperty("entityType", entityType);
    }
    public String getEntityType() {
        return (String)readProperty("entityType");
    }

    public void setId(Integer id) {
        writeProperty("id", id);
    }
    public Integer getId() {
        return (Integer)readProperty("id");
    }

    public void setIdPere(Integer idPere) {
        writeProperty("idPere", idPere);
    }
    public Integer getIdPere() {
        return (Integer)readProperty("idPere");
    }

    public void setUpdatedAt(Date updatedAt) {
        writeProperty("updatedAt", updatedAt);
    }
    public Date getUpdatedAt() {
        return (Date)readProperty("updatedAt");
    }

    public void setToSfGuardUser(SfGuardUser toSfGuardUser) {
        setToOneTarget("toSfGuardUser", toSfGuardUser, true);
    }

    public SfGuardUser getToSfGuardUser() {
        return (SfGuardUser)readProperty("toSfGuardUser");
    }


}
