package org.vamdc.kida.dao.auto;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _CounterKida was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _CounterKida extends CayenneDataObject {

    public static final String ID_PROPERTY = "id";
    public static final String MONTH_PROPERTY = "month";
    public static final String PAGE_PROPERTY = "page";
    public static final String VALUE_PROPERTY = "value";
    public static final String YEAR_PROPERTY = "year";

    public static final String ID_PK_COLUMN = "id";

    public void setId(Integer id) {
        writeProperty("id", id);
    }
    public Integer getId() {
        return (Integer)readProperty("id");
    }

    public void setMonth(Integer month) {
        writeProperty("month", month);
    }
    public Integer getMonth() {
        return (Integer)readProperty("month");
    }

    public void setPage(String page) {
        writeProperty("page", page);
    }
    public String getPage() {
        return (String)readProperty("page");
    }

    public void setValue(Integer value) {
        writeProperty("value", value);
    }
    public Integer getValue() {
        return (Integer)readProperty("value");
    }

    public void setYear(Integer year) {
        writeProperty("year", year);
    }
    public Integer getYear() {
        return (Integer)readProperty("year");
    }

}
