package org.vamdc.kida.dao.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _Documents was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Documents extends CayenneDataObject {

    public static final String CREATED_AT_PROPERTY = "createdAt";
    public static final String DESCRIPTION_PROPERTY = "description";
    public static final String FILE_DOCUMENT_PROPERTY = "fileDocument";
    public static final String FILE_PREVIEW_PROPERTY = "filePreview";
    public static final String ID_PROPERTY = "id";
    public static final String TYPE_DOCUMENT_PROPERTY = "typeDocument";
    public static final String UPDATED_AT_PROPERTY = "updatedAt";

    public static final String ID_PK_COLUMN = "id";

    public void setCreatedAt(Date createdAt) {
        writeProperty("createdAt", createdAt);
    }
    public Date getCreatedAt() {
        return (Date)readProperty("createdAt");
    }

    public void setDescription(String description) {
        writeProperty("description", description);
    }
    public String getDescription() {
        return (String)readProperty("description");
    }

    public void setFileDocument(String fileDocument) {
        writeProperty("fileDocument", fileDocument);
    }
    public String getFileDocument() {
        return (String)readProperty("fileDocument");
    }

    public void setFilePreview(String filePreview) {
        writeProperty("filePreview", filePreview);
    }
    public String getFilePreview() {
        return (String)readProperty("filePreview");
    }

    public void setId(Integer id) {
        writeProperty("id", id);
    }
    public Integer getId() {
        return (Integer)readProperty("id");
    }

    public void setTypeDocument(String typeDocument) {
        writeProperty("typeDocument", typeDocument);
    }
    public String getTypeDocument() {
        return (String)readProperty("typeDocument");
    }

    public void setUpdatedAt(Date updatedAt) {
        writeProperty("updatedAt", updatedAt);
    }
    public Date getUpdatedAt() {
        return (Date)readProperty("updatedAt");
    }

}
