package org.vamdc.kida.dao.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.vamdc.kida.dao.SpecieHasElement;

/**
 * Class _Element was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Element extends CayenneDataObject {

    public static final String ATOMIC_NUMBER_PROPERTY = "atomicNumber";
    public static final String CREATED_AT_PROPERTY = "createdAt";
    public static final String ID_PROPERTY = "id";
    public static final String MASS_VALUE_PROPERTY = "massValue";
    public static final String NAME_PROPERTY = "name";
    public static final String SYMBOL_PROPERTY = "symbol";
    public static final String UPDATED_AT_PROPERTY = "updatedAt";
    public static final String SPECIE_HAS_ELEMENTS_PROPERTY = "specieHasElements";

    public static final String ID_PK_COLUMN = "id";

    public void setAtomicNumber(Integer atomicNumber) {
        writeProperty("atomicNumber", atomicNumber);
    }
    public Integer getAtomicNumber() {
        return (Integer)readProperty("atomicNumber");
    }

    public void setCreatedAt(Date createdAt) {
        writeProperty("createdAt", createdAt);
    }
    public Date getCreatedAt() {
        return (Date)readProperty("createdAt");
    }

    public void setId(Integer id) {
        writeProperty("id", id);
    }
    public Integer getId() {
        return (Integer)readProperty("id");
    }

    public void setMassValue(Double massValue) {
        writeProperty("massValue", massValue);
    }
    public Double getMassValue() {
        return (Double)readProperty("massValue");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setSymbol(String symbol) {
        writeProperty("symbol", symbol);
    }
    public String getSymbol() {
        return (String)readProperty("symbol");
    }

    public void setUpdatedAt(Date updatedAt) {
        writeProperty("updatedAt", updatedAt);
    }
    public Date getUpdatedAt() {
        return (Date)readProperty("updatedAt");
    }

    public void addToSpecieHasElements(SpecieHasElement obj) {
        addToManyTarget("specieHasElements", obj, true);
    }
    public void removeFromSpecieHasElements(SpecieHasElement obj) {
        removeToManyTarget("specieHasElements", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<SpecieHasElement> getSpecieHasElements() {
        return (List<SpecieHasElement>)readProperty("specieHasElements");
    }


}
