package org.vamdc.kida.dao.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.vamdc.kida.dao.Channel;
import org.vamdc.kida.dao.Reaction;

/**
 * Class _ExperimentHasChannel was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ExperimentHasChannel extends CayenneDataObject {

    public static final String CHANNEL_ID_PROPERTY = "channelId";
    public static final String CREATED_AT_PROPERTY = "createdAt";
    public static final String REACTION_ID_PROPERTY = "reactionId";
    public static final String UPDATED_AT_PROPERTY = "updatedAt";
    public static final String CHANNEL_PROPERTY = "channel";
    public static final String REACTION_PROPERTY = "reaction";

    public static final String CHANNEL_ID_PK_COLUMN = "channel_id";
    public static final String REACTION_ID_PK_COLUMN = "reaction_id";

    public void setChannelId(Integer channelId) {
        writeProperty("channelId", channelId);
    }
    public Integer getChannelId() {
        return (Integer)readProperty("channelId");
    }

    public void setCreatedAt(Date createdAt) {
        writeProperty("createdAt", createdAt);
    }
    public Date getCreatedAt() {
        return (Date)readProperty("createdAt");
    }

    public void setReactionId(Integer reactionId) {
        writeProperty("reactionId", reactionId);
    }
    public Integer getReactionId() {
        return (Integer)readProperty("reactionId");
    }

    public void setUpdatedAt(Date updatedAt) {
        writeProperty("updatedAt", updatedAt);
    }
    public Date getUpdatedAt() {
        return (Date)readProperty("updatedAt");
    }

    public void setChannel(Channel channel) {
        setToOneTarget("channel", channel, true);
    }

    public Channel getChannel() {
        return (Channel)readProperty("channel");
    }


    public void setReaction(Reaction reaction) {
        setToOneTarget("reaction", reaction, true);
    }

    public Reaction getReaction() {
        return (Reaction)readProperty("reaction");
    }


}
