package org.vamdc.kida.dao.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _HistoChannelValue was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _HistoChannelValue extends CayenneDataObject {

    public static final String ACTION_PROPERTY = "action";
    public static final String ADD_JUSTIFICATION_PROPERTY = "addJustification";
    public static final String AUTHOR_EMAIL_PROPERTY = "authorEmail";
    public static final String BIBLIOGRAPHY_ID_PROPERTY = "bibliographyId";
    public static final String CHANNEL_ID_PROPERTY = "channelId";
    public static final String DATE_ACTION_PROPERTY = "dateAction";
    public static final String DESCRIPTION_PROPERTY = "description";
    public static final String EXPERT_AUTHORISED_PROPERTY = "expertAuthorised";
    public static final String EXPERT_EMAIL_PROPERTY = "expertEmail";
    public static final String EXPERTIZE_PROPERTY = "expertize";
    public static final String FORMULA_ID_PROPERTY = "formulaId";
    public static final String ID_PROPERTY = "id";
    public static final String ID_ORIGINAL_PROPERTY = "idOriginal";
    public static final String JUSTIFICATION_PROPERTY = "justification";
    public static final String METHOD_PROPERTY = "method";
    public static final String ORIGIN_PROPERTY = "origin";
    public static final String REF_PROPERTY = "ref";
    public static final String STATUS_PROPERTY = "status";
    public static final String VALIDITY_RANGE_ID_PROPERTY = "validityRangeId";

    public static final String ID_PK_COLUMN = "id";

    public void setAction(String action) {
        writeProperty("action", action);
    }
    public String getAction() {
        return (String)readProperty("action");
    }

    public void setAddJustification(String addJustification) {
        writeProperty("addJustification", addJustification);
    }
    public String getAddJustification() {
        return (String)readProperty("addJustification");
    }

    public void setAuthorEmail(String authorEmail) {
        writeProperty("authorEmail", authorEmail);
    }
    public String getAuthorEmail() {
        return (String)readProperty("authorEmail");
    }

    public void setBibliographyId(Integer bibliographyId) {
        writeProperty("bibliographyId", bibliographyId);
    }
    public Integer getBibliographyId() {
        return (Integer)readProperty("bibliographyId");
    }

    public void setChannelId(Integer channelId) {
        writeProperty("channelId", channelId);
    }
    public Integer getChannelId() {
        return (Integer)readProperty("channelId");
    }

    public void setDateAction(Date dateAction) {
        writeProperty("dateAction", dateAction);
    }
    public Date getDateAction() {
        return (Date)readProperty("dateAction");
    }

    public void setDescription(String description) {
        writeProperty("description", description);
    }
    public String getDescription() {
        return (String)readProperty("description");
    }

    public void setExpertAuthorised(String expertAuthorised) {
        writeProperty("expertAuthorised", expertAuthorised);
    }
    public String getExpertAuthorised() {
        return (String)readProperty("expertAuthorised");
    }

    public void setExpertEmail(String expertEmail) {
        writeProperty("expertEmail", expertEmail);
    }
    public String getExpertEmail() {
        return (String)readProperty("expertEmail");
    }

    public void setExpertize(Integer expertize) {
        writeProperty("expertize", expertize);
    }
    public Integer getExpertize() {
        return (Integer)readProperty("expertize");
    }

    public void setFormulaId(Integer formulaId) {
        writeProperty("formulaId", formulaId);
    }
    public Integer getFormulaId() {
        return (Integer)readProperty("formulaId");
    }

    public void setId(Integer id) {
        writeProperty("id", id);
    }
    public Integer getId() {
        return (Integer)readProperty("id");
    }

    public void setIdOriginal(Integer idOriginal) {
        writeProperty("idOriginal", idOriginal);
    }
    public Integer getIdOriginal() {
        return (Integer)readProperty("idOriginal");
    }

    public void setJustification(String justification) {
        writeProperty("justification", justification);
    }
    public String getJustification() {
        return (String)readProperty("justification");
    }

    public void setMethod(String method) {
        writeProperty("method", method);
    }
    public String getMethod() {
        return (String)readProperty("method");
    }

    public void setOrigin(String origin) {
        writeProperty("origin", origin);
    }
    public String getOrigin() {
        return (String)readProperty("origin");
    }

    public void setRef(String ref) {
        writeProperty("ref", ref);
    }
    public String getRef() {
        return (String)readProperty("ref");
    }

    public void setStatus(Integer status) {
        writeProperty("status", status);
    }
    public Integer getStatus() {
        return (Integer)readProperty("status");
    }

    public void setValidityRangeId(Integer validityRangeId) {
        writeProperty("validityRangeId", validityRangeId);
    }
    public Integer getValidityRangeId() {
        return (Integer)readProperty("validityRangeId");
    }

}
