package org.vamdc.kida.dao.auto;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _ImportCheckSpecies was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ImportCheckSpecies extends CayenneDataObject {

    public static final String ID_PROPERTY = "id";
    public static final String SPECIES_PROPERTY = "species";

    public static final String ID_PK_COLUMN = "id";

    public void setId(Integer id) {
        writeProperty("id", id);
    }
    public Integer getId() {
        return (Integer)readProperty("id");
    }

    public void setSpecies(String species) {
        writeProperty("species", species);
    }
    public String getSpecies() {
        return (String)readProperty("species");
    }

}
