package org.vamdc.kida.dao.auto;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _KinfValue was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _KinfValue extends CayenneDataObject {

    public static final String BIBLIOGRAPHY_ID_PROPERTY = "bibliographyId";
    public static final String CHANNEL_VALUE_ID_PROPERTY = "channelValueId";
    public static final String DATABASE_PROPERTY = "database";
    public static final String DESCRIPTION_PROPERTY = "description";
    public static final String EXPOSANT_A_PROPERTY = "exposantA";
    public static final String EXPOSANT_B_PROPERTY = "exposantB";
    public static final String EXPOSANT_N_PROPERTY = "exposantN";
    public static final String F0_PROPERTY = "f0";
    public static final String FORMULA_ID_PROPERTY = "formulaId";
    public static final String G_PROPERTY = "g";
    public static final String ID_PROPERTY = "id";
    public static final String METHOD_PROPERTY = "method";
    public static final String ORIGIN_PROPERTY = "origin";
    public static final String TYPE_UNCERT_PROPERTY = "typeUncert";
    public static final String VALUE_A_PROPERTY = "valueA";
    public static final String VALUE_B_PROPERTY = "valueB";
    public static final String VALUE_N_PROPERTY = "valueN";

    public static final String ID_PK_COLUMN = "id";

    public void setBibliographyId(Integer bibliographyId) {
        writeProperty("bibliographyId", bibliographyId);
    }
    public Integer getBibliographyId() {
        return (Integer)readProperty("bibliographyId");
    }

    public void setChannelValueId(Integer channelValueId) {
        writeProperty("channelValueId", channelValueId);
    }
    public Integer getChannelValueId() {
        return (Integer)readProperty("channelValueId");
    }

    public void setDatabase(String database) {
        writeProperty("database", database);
    }
    public String getDatabase() {
        return (String)readProperty("database");
    }

    public void setDescription(String description) {
        writeProperty("description", description);
    }
    public String getDescription() {
        return (String)readProperty("description");
    }

    public void setExposantA(Integer exposantA) {
        writeProperty("exposantA", exposantA);
    }
    public Integer getExposantA() {
        return (Integer)readProperty("exposantA");
    }

    public void setExposantB(Integer exposantB) {
        writeProperty("exposantB", exposantB);
    }
    public Integer getExposantB() {
        return (Integer)readProperty("exposantB");
    }

    public void setExposantN(Integer exposantN) {
        writeProperty("exposantN", exposantN);
    }
    public Integer getExposantN() {
        return (Integer)readProperty("exposantN");
    }

    public void setF0(Float f0) {
        writeProperty("f0", f0);
    }
    public Float getF0() {
        return (Float)readProperty("f0");
    }

    public void setFormulaId(Integer formulaId) {
        writeProperty("formulaId", formulaId);
    }
    public Integer getFormulaId() {
        return (Integer)readProperty("formulaId");
    }

    public void setG(Float g) {
        writeProperty("g", g);
    }
    public Float getG() {
        return (Float)readProperty("g");
    }

    public void setId(Integer id) {
        writeProperty("id", id);
    }
    public Integer getId() {
        return (Integer)readProperty("id");
    }

    public void setMethod(String method) {
        writeProperty("method", method);
    }
    public String getMethod() {
        return (String)readProperty("method");
    }

    public void setOrigin(String origin) {
        writeProperty("origin", origin);
    }
    public String getOrigin() {
        return (String)readProperty("origin");
    }

    public void setTypeUncert(String typeUncert) {
        writeProperty("typeUncert", typeUncert);
    }
    public String getTypeUncert() {
        return (String)readProperty("typeUncert");
    }

    public void setValueA(Float valueA) {
        writeProperty("valueA", valueA);
    }
    public Float getValueA() {
        return (Float)readProperty("valueA");
    }

    public void setValueB(Float valueB) {
        writeProperty("valueB", valueB);
    }
    public Float getValueB() {
        return (Float)readProperty("valueB");
    }

    public void setValueN(Float valueN) {
        writeProperty("valueN", valueN);
    }
    public Float getValueN() {
        return (Float)readProperty("valueN");
    }

}
