package org.vamdc.kida.dao.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.vamdc.kida.dao.Datasheet;
import org.vamdc.kida.dao.ExperimentHasChannel;
import org.vamdc.kida.dao.ThreeBodyReaction;
import org.vamdc.kida.dao.TotalRate;

/**
 * Class _Reaction was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Reaction extends CayenneDataObject {

    public static final String ADDED_STATUS_PROPERTY = "addedStatus";
    public static final String CREATED_AT_PROPERTY = "createdAt";
    public static final String ID_PROPERTY = "id";
    public static final String UPDATED_AT_PROPERTY = "updatedAt";
    public static final String DATASHEETS_PROPERTY = "datasheets";
    public static final String EXPERIMENT_HAS_CHANNELS_PROPERTY = "experimentHasChannels";
    public static final String THREE_BODY_REACTION_PROPERTY = "threeBodyReaction";
    public static final String TOTAL_RATES_PROPERTY = "totalRates";

    public static final String ID_PK_COLUMN = "id";

    public void setAddedStatus(Integer addedStatus) {
        writeProperty("addedStatus", addedStatus);
    }
    public Integer getAddedStatus() {
        return (Integer)readProperty("addedStatus");
    }

    public void setCreatedAt(Date createdAt) {
        writeProperty("createdAt", createdAt);
    }
    public Date getCreatedAt() {
        return (Date)readProperty("createdAt");
    }

    public void setId(Integer id) {
        writeProperty("id", id);
    }
    public Integer getId() {
        return (Integer)readProperty("id");
    }

    public void setUpdatedAt(Date updatedAt) {
        writeProperty("updatedAt", updatedAt);
    }
    public Date getUpdatedAt() {
        return (Date)readProperty("updatedAt");
    }

    public void addToDatasheets(Datasheet obj) {
        addToManyTarget("datasheets", obj, true);
    }
    public void removeFromDatasheets(Datasheet obj) {
        removeToManyTarget("datasheets", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Datasheet> getDatasheets() {
        return (List<Datasheet>)readProperty("datasheets");
    }


    public void addToExperimentHasChannels(ExperimentHasChannel obj) {
        addToManyTarget("experimentHasChannels", obj, true);
    }
    public void removeFromExperimentHasChannels(ExperimentHasChannel obj) {
        removeToManyTarget("experimentHasChannels", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<ExperimentHasChannel> getExperimentHasChannels() {
        return (List<ExperimentHasChannel>)readProperty("experimentHasChannels");
    }


    public void setThreeBodyReaction(ThreeBodyReaction threeBodyReaction) {
        setToOneTarget("threeBodyReaction", threeBodyReaction, true);
    }

    public ThreeBodyReaction getThreeBodyReaction() {
        return (ThreeBodyReaction)readProperty("threeBodyReaction");
    }


    public void addToTotalRates(TotalRate obj) {
        addToManyTarget("totalRates", obj, true);
    }
    public void removeFromTotalRates(TotalRate obj) {
        removeToManyTarget("totalRates", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<TotalRate> getTotalRates() {
        return (List<TotalRate>)readProperty("totalRates");
    }


}
