package org.vamdc.kida.dao.auto;

import org.apache.cayenne.CayenneDataObject;
import org.vamdc.kida.dao.SfGuardGroup;
import org.vamdc.kida.dao.SfGuardUser;

/**
 * Class _SfGuardUserGroup was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _SfGuardUserGroup extends CayenneDataObject {

    public static final String GROUP_ID_PROPERTY = "groupId";
    public static final String USER_ID_PROPERTY = "userId";
    public static final String GROUP_PROPERTY = "group";
    public static final String USER_PROPERTY = "user";

    public static final String GROUP_ID_PK_COLUMN = "group_id";
    public static final String USER_ID_PK_COLUMN = "user_id";

    public void setGroupId(Integer groupId) {
        writeProperty("groupId", groupId);
    }
    public Integer getGroupId() {
        return (Integer)readProperty("groupId");
    }

    public void setUserId(Integer userId) {
        writeProperty("userId", userId);
    }
    public Integer getUserId() {
        return (Integer)readProperty("userId");
    }

    public void setGroup(SfGuardGroup group) {
        setToOneTarget("group", group, true);
    }

    public SfGuardGroup getGroup() {
        return (SfGuardGroup)readProperty("group");
    }


    public void setUser(SfGuardUser user) {
        setToOneTarget("user", user, true);
    }

    public SfGuardUser getUser() {
        return (SfGuardUser)readProperty("user");
    }


}
