package org.vamdc.kida.dao.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.vamdc.kida.dao.SfGuardUser;

/**
 * Class _SfGuardUserProfile was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _SfGuardUserProfile extends CayenneDataObject {

    public static final String CREATED_AT_PROPERTY = "createdAt";
    public static final String FIRST_NAME_PROPERTY = "firstName";
    public static final String ID_PROPERTY = "id";
    public static final String LAST_NAME_PROPERTY = "lastName";
    public static final String UPDATED_AT_PROPERTY = "updatedAt";
    public static final String USER_PROPERTY = "user";

    public static final String ID_PK_COLUMN = "id";

    public void setCreatedAt(Date createdAt) {
        writeProperty("createdAt", createdAt);
    }
    public Date getCreatedAt() {
        return (Date)readProperty("createdAt");
    }

    public void setFirstName(String firstName) {
        writeProperty("firstName", firstName);
    }
    public String getFirstName() {
        return (String)readProperty("firstName");
    }

    public void setId(Integer id) {
        writeProperty("id", id);
    }
    public Integer getId() {
        return (Integer)readProperty("id");
    }

    public void setLastName(String lastName) {
        writeProperty("lastName", lastName);
    }
    public String getLastName() {
        return (String)readProperty("lastName");
    }

    public void setUpdatedAt(Date updatedAt) {
        writeProperty("updatedAt", updatedAt);
    }
    public Date getUpdatedAt() {
        return (Date)readProperty("updatedAt");
    }

    public void setUser(SfGuardUser user) {
        setToOneTarget("user", user, true);
    }

    public SfGuardUser getUser() {
        return (SfGuardUser)readProperty("user");
    }


}
