package org.vamdc.kida.dao.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.vamdc.kida.dao.SfGuardUser;

/**
 * Class _SfGuardRememberKey was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _SfGuardRememberKey extends CayenneDataObject {

    public static final String CREATED_AT_PROPERTY = "createdAt";
    public static final String IP_ADDRESS_PROPERTY = "ipAddress";
    public static final String REMEMBER_KEY_PROPERTY = "rememberKey";
    public static final String USER_ID_PROPERTY = "userId";
    public static final String USER_PROPERTY = "user";

    public static final String IP_ADDRESS_PK_COLUMN = "ip_address";
    public static final String USER_ID_PK_COLUMN = "user_id";

    public void setCreatedAt(Date createdAt) {
        writeProperty("createdAt", createdAt);
    }
    public Date getCreatedAt() {
        return (Date)readProperty("createdAt");
    }

    public void setIpAddress(String ipAddress) {
        writeProperty("ipAddress", ipAddress);
    }
    public String getIpAddress() {
        return (String)readProperty("ipAddress");
    }

    public void setRememberKey(String rememberKey) {
        writeProperty("rememberKey", rememberKey);
    }
    public String getRememberKey() {
        return (String)readProperty("rememberKey");
    }

    public void setUserId(Integer userId) {
        writeProperty("userId", userId);
    }
    public Integer getUserId() {
        return (Integer)readProperty("userId");
    }

    public void setUser(SfGuardUser user) {
        setToOneTarget("user", user, true);
    }

    public SfGuardUser getUser() {
        return (SfGuardUser)readProperty("user");
    }


}
