package org.vamdc.kida.dao.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.vamdc.kida.dao.SfGuardGroupPermission;
import org.vamdc.kida.dao.SfGuardUserGroup;

/**
 * Class _SfGuardGroup was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _SfGuardGroup extends CayenneDataObject {

    public static final String DESCRIPTION_PROPERTY = "description";
    public static final String ID_PROPERTY = "id";
    public static final String NAME_PROPERTY = "name";
    public static final String SF_GUARD_GROUP_PERMISSIONS_PROPERTY = "sfGuardGroupPermissions";
    public static final String SF_GUARD_USER_GROUPS_PROPERTY = "sfGuardUserGroups";

    public static final String ID_PK_COLUMN = "id";

    public void setDescription(String description) {
        writeProperty("description", description);
    }
    public String getDescription() {
        return (String)readProperty("description");
    }

    public void setId(Integer id) {
        writeProperty("id", id);
    }
    public Integer getId() {
        return (Integer)readProperty("id");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void addToSfGuardGroupPermissions(SfGuardGroupPermission obj) {
        addToManyTarget("sfGuardGroupPermissions", obj, true);
    }
    public void removeFromSfGuardGroupPermissions(SfGuardGroupPermission obj) {
        removeToManyTarget("sfGuardGroupPermissions", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<SfGuardGroupPermission> getSfGuardGroupPermissions() {
        return (List<SfGuardGroupPermission>)readProperty("sfGuardGroupPermissions");
    }


    public void addToSfGuardUserGroups(SfGuardUserGroup obj) {
        addToManyTarget("sfGuardUserGroups", obj, true);
    }
    public void removeFromSfGuardUserGroups(SfGuardUserGroup obj) {
        removeToManyTarget("sfGuardUserGroups", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<SfGuardUserGroup> getSfGuardUserGroups() {
        return (List<SfGuardUserGroup>)readProperty("sfGuardUserGroups");
    }


}
