package org.vamdc.kida.dao.auto;

import org.apache.cayenne.CayenneDataObject;
import org.vamdc.kida.dao.SfGuardGroup;
import org.vamdc.kida.dao.SfGuardPermission;

/**
 * Class _SfGuardGroupPermission was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _SfGuardGroupPermission extends CayenneDataObject {

    public static final String GROUP_ID_PROPERTY = "groupId";
    public static final String PERMISSION_ID_PROPERTY = "permissionId";
    public static final String GROUP_PROPERTY = "group";
    public static final String PERMISSION_PROPERTY = "permission";

    public static final String GROUP_ID_PK_COLUMN = "group_id";
    public static final String PERMISSION_ID_PK_COLUMN = "permission_id";

    public void setGroupId(Integer groupId) {
        writeProperty("groupId", groupId);
    }
    public Integer getGroupId() {
        return (Integer)readProperty("groupId");
    }

    public void setPermissionId(Integer permissionId) {
        writeProperty("permissionId", permissionId);
    }
    public Integer getPermissionId() {
        return (Integer)readProperty("permissionId");
    }

    public void setGroup(SfGuardGroup group) {
        setToOneTarget("group", group, true);
    }

    public SfGuardGroup getGroup() {
        return (SfGuardGroup)readProperty("group");
    }


    public void setPermission(SfGuardPermission permission) {
        setToOneTarget("permission", permission, true);
    }

    public SfGuardPermission getPermission() {
        return (SfGuardPermission)readProperty("permission");
    }


}
