package org.vamdc.kida.dao.auto;

import org.apache.cayenne.CayenneDataObject;
import org.vamdc.kida.dao.SfGuardPermission;
import org.vamdc.kida.dao.SfGuardUser;

/**
 * Class _SfGuardUserPermission was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _SfGuardUserPermission extends CayenneDataObject {

    public static final String PERMISSION_ID_PROPERTY = "permissionId";
    public static final String USER_ID_PROPERTY = "userId";
    public static final String PERMISSION_PROPERTY = "permission";
    public static final String USER_PROPERTY = "user";

    public static final String PERMISSION_ID_PK_COLUMN = "permission_id";
    public static final String USER_ID_PK_COLUMN = "user_id";

    public void setPermissionId(Integer permissionId) {
        writeProperty("permissionId", permissionId);
    }
    public Integer getPermissionId() {
        return (Integer)readProperty("permissionId");
    }

    public void setUserId(Integer userId) {
        writeProperty("userId", userId);
    }
    public Integer getUserId() {
        return (Integer)readProperty("userId");
    }

    public void setPermission(SfGuardPermission permission) {
        setToOneTarget("permission", permission, true);
    }

    public SfGuardPermission getPermission() {
        return (SfGuardPermission)readProperty("permission");
    }


    public void setUser(SfGuardUser user) {
        setToOneTarget("user", user, true);
    }

    public SfGuardUser getUser() {
        return (SfGuardUser)readProperty("user");
    }


}
