package org.vamdc.kida.dao.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.vamdc.kida.dao.Element;
import org.vamdc.kida.dao.Specie;

/**
 * Class _SpecieHasElement was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _SpecieHasElement extends CayenneDataObject {

    public static final String CREATED_AT_PROPERTY = "createdAt";
    public static final String ELEMENT_ID_PROPERTY = "elementId";
    public static final String OCCURRENCE_PROPERTY = "occurrence";
    public static final String SPECIE_ID_PROPERTY = "specieId";
    public static final String UPDATED_AT_PROPERTY = "updatedAt";
    public static final String ELEMENT_PROPERTY = "element";
    public static final String SPECIE_PROPERTY = "specie";

    public static final String ELEMENT_ID_PK_COLUMN = "element_id";
    public static final String SPECIE_ID_PK_COLUMN = "specie_id";

    public void setCreatedAt(Date createdAt) {
        writeProperty("createdAt", createdAt);
    }
    public Date getCreatedAt() {
        return (Date)readProperty("createdAt");
    }

    public void setElementId(Integer elementId) {
        writeProperty("elementId", elementId);
    }
    public Integer getElementId() {
        return (Integer)readProperty("elementId");
    }

    public void setOccurrence(Integer occurrence) {
        writeProperty("occurrence", occurrence);
    }
    public Integer getOccurrence() {
        return (Integer)readProperty("occurrence");
    }

    public void setSpecieId(Integer specieId) {
        writeProperty("specieId", specieId);
    }
    public Integer getSpecieId() {
        return (Integer)readProperty("specieId");
    }

    public void setUpdatedAt(Date updatedAt) {
        writeProperty("updatedAt", updatedAt);
    }
    public Date getUpdatedAt() {
        return (Date)readProperty("updatedAt");
    }

    public void setElement(Element element) {
        setToOneTarget("element", element, true);
    }

    public Element getElement() {
        return (Element)readProperty("element");
    }


    public void setSpecie(Specie specie) {
        setToOneTarget("specie", specie, true);
    }

    public Specie getSpecie() {
        return (Specie)readProperty("specie");
    }


}
