package org.vamdc.kida.dao.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.vamdc.kida.dao.Reaction;
import org.vamdc.kida.dao.ThreeBodyReactionHasChannel;

/**
 * Class _ThreeBodyReaction was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ThreeBodyReaction extends CayenneDataObject {

    public static final String CREATED_AT_PROPERTY = "createdAt";
    public static final String ID_PROPERTY = "id";
    public static final String UPDATED_AT_PROPERTY = "updatedAt";
    public static final String REACTIONS_PROPERTY = "reactions";
    public static final String THREE_BODY_REACTION_HAS_CHANNELS_PROPERTY = "threeBodyReactionHasChannels";

    public static final String ID_PK_COLUMN = "id";

    public void setCreatedAt(Date createdAt) {
        writeProperty("createdAt", createdAt);
    }
    public Date getCreatedAt() {
        return (Date)readProperty("createdAt");
    }

    public void setId(Integer id) {
        writeProperty("id", id);
    }
    public Integer getId() {
        return (Integer)readProperty("id");
    }

    public void setUpdatedAt(Date updatedAt) {
        writeProperty("updatedAt", updatedAt);
    }
    public Date getUpdatedAt() {
        return (Date)readProperty("updatedAt");
    }

    public void addToReactions(Reaction obj) {
        addToManyTarget("reactions", obj, true);
    }
    public void removeFromReactions(Reaction obj) {
        removeToManyTarget("reactions", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Reaction> getReactions() {
        return (List<Reaction>)readProperty("reactions");
    }


    public void addToThreeBodyReactionHasChannels(ThreeBodyReactionHasChannel obj) {
        addToManyTarget("threeBodyReactionHasChannels", obj, true);
    }
    public void removeFromThreeBodyReactionHasChannels(ThreeBodyReactionHasChannel obj) {
        removeToManyTarget("threeBodyReactionHasChannels", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<ThreeBodyReactionHasChannel> getThreeBodyReactionHasChannels() {
        return (List<ThreeBodyReactionHasChannel>)readProperty("threeBodyReactionHasChannels");
    }


}
