package org.vamdc.kida.dao.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.vamdc.kida.dao.ThreeBodyChannelHasSpecie;
import org.vamdc.kida.dao.ThreeBodyReactionHasChannel;
import org.vamdc.kida.dao.ThreeBodyReactionHasReactant;

/**
 * Class _ThreeBodyChannel was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ThreeBodyChannel extends CayenneDataObject {

    public static final String CREATED_AT_PROPERTY = "createdAt";
    public static final String ID_PROPERTY = "id";
    public static final String STATUS_PROPERTY = "status";
    public static final String UPDATED_AT_PROPERTY = "updatedAt";
    public static final String THREE_BODY_CHANNEL_HAS_SPECIES_PROPERTY = "threeBodyChannelHasSpecies";
    public static final String THREE_BODY_REACTION_HAS_CHANNELS_PROPERTY = "threeBodyReactionHasChannels";
    public static final String THREE_BODY_REACTION_HAS_REACTANTS_PROPERTY = "threeBodyReactionHasReactants";

    public static final String ID_PK_COLUMN = "id";

    public void setCreatedAt(Date createdAt) {
        writeProperty("createdAt", createdAt);
    }
    public Date getCreatedAt() {
        return (Date)readProperty("createdAt");
    }

    public void setId(Integer id) {
        writeProperty("id", id);
    }
    public Integer getId() {
        return (Integer)readProperty("id");
    }

    public void setStatus(String status) {
        writeProperty("status", status);
    }
    public String getStatus() {
        return (String)readProperty("status");
    }

    public void setUpdatedAt(Date updatedAt) {
        writeProperty("updatedAt", updatedAt);
    }
    public Date getUpdatedAt() {
        return (Date)readProperty("updatedAt");
    }

    public void addToThreeBodyChannelHasSpecies(ThreeBodyChannelHasSpecie obj) {
        addToManyTarget("threeBodyChannelHasSpecies", obj, true);
    }
    public void removeFromThreeBodyChannelHasSpecies(ThreeBodyChannelHasSpecie obj) {
        removeToManyTarget("threeBodyChannelHasSpecies", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<ThreeBodyChannelHasSpecie> getThreeBodyChannelHasSpecies() {
        return (List<ThreeBodyChannelHasSpecie>)readProperty("threeBodyChannelHasSpecies");
    }


    public void addToThreeBodyReactionHasChannels(ThreeBodyReactionHasChannel obj) {
        addToManyTarget("threeBodyReactionHasChannels", obj, true);
    }
    public void removeFromThreeBodyReactionHasChannels(ThreeBodyReactionHasChannel obj) {
        removeToManyTarget("threeBodyReactionHasChannels", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<ThreeBodyReactionHasChannel> getThreeBodyReactionHasChannels() {
        return (List<ThreeBodyReactionHasChannel>)readProperty("threeBodyReactionHasChannels");
    }


    public void addToThreeBodyReactionHasReactants(ThreeBodyReactionHasReactant obj) {
        addToManyTarget("threeBodyReactionHasReactants", obj, true);
    }
    public void removeFromThreeBodyReactionHasReactants(ThreeBodyReactionHasReactant obj) {
        removeToManyTarget("threeBodyReactionHasReactants", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<ThreeBodyReactionHasReactant> getThreeBodyReactionHasReactants() {
        return (List<ThreeBodyReactionHasReactant>)readProperty("threeBodyReactionHasReactants");
    }


}
