package org.vamdc.kida.dao.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.vamdc.kida.dao.ChannelVariable;
import org.vamdc.kida.dao.Reaction;
import org.vamdc.kida.dao.SfGuardUser;
import org.vamdc.kida.dao.ValidityRange;

/**
 * Class _TotalRate was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _TotalRate extends CayenneDataObject {

    public static final String CREATED_AT_PROPERTY = "createdAt";
    public static final String EXPERTIZE_PROPERTY = "expertize";
    public static final String ID_PROPERTY = "id";
    public static final String JUSTIFICATION_PROPERTY = "justification";
    public static final String METHOD_PROPERTY = "method";
    public static final String ORIGIN_PROPERTY = "origin";
    public static final String UPDATED_AT_PROPERTY = "updatedAt";
    public static final String CHANNEL_VARIABLES_PROPERTY = "channelVariables";
    public static final String REACTION_PROPERTY = "reaction";
    public static final String TO_SF_GUARD_USER_PROPERTY = "toSfGuardUser";
    public static final String TO_SF_GUARD_USER1_PROPERTY = "toSfGuardUser1";
    public static final String VALIDITY_RANGE_PROPERTY = "validityRange";

    public static final String ID_PK_COLUMN = "id";

    public void setCreatedAt(Date createdAt) {
        writeProperty("createdAt", createdAt);
    }
    public Date getCreatedAt() {
        return (Date)readProperty("createdAt");
    }

    public void setExpertize(Integer expertize) {
        writeProperty("expertize", expertize);
    }
    public Integer getExpertize() {
        return (Integer)readProperty("expertize");
    }

    public void setId(Integer id) {
        writeProperty("id", id);
    }
    public Integer getId() {
        return (Integer)readProperty("id");
    }

    public void setJustification(String justification) {
        writeProperty("justification", justification);
    }
    public String getJustification() {
        return (String)readProperty("justification");
    }

    public void setMethod(String method) {
        writeProperty("method", method);
    }
    public String getMethod() {
        return (String)readProperty("method");
    }

    public void setOrigin(String origin) {
        writeProperty("origin", origin);
    }
    public String getOrigin() {
        return (String)readProperty("origin");
    }

    public void setUpdatedAt(Date updatedAt) {
        writeProperty("updatedAt", updatedAt);
    }
    public Date getUpdatedAt() {
        return (Date)readProperty("updatedAt");
    }

    public void addToChannelVariables(ChannelVariable obj) {
        addToManyTarget("channelVariables", obj, true);
    }
    public void removeFromChannelVariables(ChannelVariable obj) {
        removeToManyTarget("channelVariables", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<ChannelVariable> getChannelVariables() {
        return (List<ChannelVariable>)readProperty("channelVariables");
    }


    public void setReaction(Reaction reaction) {
        setToOneTarget("reaction", reaction, true);
    }

    public Reaction getReaction() {
        return (Reaction)readProperty("reaction");
    }


    public void setToSfGuardUser(SfGuardUser toSfGuardUser) {
        setToOneTarget("toSfGuardUser", toSfGuardUser, true);
    }

    public SfGuardUser getToSfGuardUser() {
        return (SfGuardUser)readProperty("toSfGuardUser");
    }


    public void setToSfGuardUser1(SfGuardUser toSfGuardUser1) {
        setToOneTarget("toSfGuardUser1", toSfGuardUser1, true);
    }

    public SfGuardUser getToSfGuardUser1() {
        return (SfGuardUser)readProperty("toSfGuardUser1");
    }


    public void setValidityRange(ValidityRange validityRange) {
        setToOneTarget("validityRange", validityRange, true);
    }

    public ValidityRange getValidityRange() {
        return (ValidityRange)readProperty("validityRange");
    }


}
