package org.vamdc.kida.dao.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.vamdc.kida.dao.ChannelValue;
import org.vamdc.kida.dao.TotalRate;

/**
 * Class _ValidityRange was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ValidityRange extends CayenneDataObject {

    public static final String CREATED_AT_PROPERTY = "createdAt";
    public static final String ID_PROPERTY = "id";
    public static final String PMAX_PROPERTY = "pmax";
    public static final String PMIN_PROPERTY = "pmin";
    public static final String TMAX_PROPERTY = "tmax";
    public static final String TMIN_PROPERTY = "tmin";
    public static final String UPDATED_AT_PROPERTY = "updatedAt";
    public static final String CHANNEL_VALUES_PROPERTY = "channelValues";
    public static final String TOTAL_RATES_PROPERTY = "totalRates";

    public static final String ID_PK_COLUMN = "id";

    public void setCreatedAt(Date createdAt) {
        writeProperty("createdAt", createdAt);
    }
    public Date getCreatedAt() {
        return (Date)readProperty("createdAt");
    }

    public void setId(Integer id) {
        writeProperty("id", id);
    }
    public Integer getId() {
        return (Integer)readProperty("id");
    }

    public void setPmax(Integer pmax) {
        writeProperty("pmax", pmax);
    }
    public Integer getPmax() {
        return (Integer)readProperty("pmax");
    }

    public void setPmin(Integer pmin) {
        writeProperty("pmin", pmin);
    }
    public Integer getPmin() {
        return (Integer)readProperty("pmin");
    }

    public void setTmax(Integer tmax) {
        writeProperty("tmax", tmax);
    }
    public Integer getTmax() {
        return (Integer)readProperty("tmax");
    }

    public void setTmin(Integer tmin) {
        writeProperty("tmin", tmin);
    }
    public Integer getTmin() {
        return (Integer)readProperty("tmin");
    }

    public void setUpdatedAt(Date updatedAt) {
        writeProperty("updatedAt", updatedAt);
    }
    public Date getUpdatedAt() {
        return (Date)readProperty("updatedAt");
    }

    public void addToChannelValues(ChannelValue obj) {
        addToManyTarget("channelValues", obj, true);
    }
    public void removeFromChannelValues(ChannelValue obj) {
        removeToManyTarget("channelValues", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<ChannelValue> getChannelValues() {
        return (List<ChannelValue>)readProperty("channelValues");
    }


    public void addToTotalRates(TotalRate obj) {
        addToManyTarget("totalRates", obj, true);
    }
    public void removeFromTotalRates(TotalRate obj) {
        removeToManyTarget("totalRates", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<TotalRate> getTotalRates() {
        return (List<TotalRate>)readProperty("totalRates");
    }


}
