package org.vamdc.kida.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.vamdc.kida.BiblioBook;
import org.vamdc.kida.BiblioJournal;
import org.vamdc.kida.BiblioThesis;
import org.vamdc.kida.ChannelValue;
import org.vamdc.kida.FcValue;
import org.vamdc.kida.K0Value;
import org.vamdc.kida.KinfValue;

/**
 * Class _Biblio was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Biblio extends CayenneDataObject {

    public static final String AUTHORS_PROPERTY = "authors";
    public static final String CREATED_AT_PROPERTY = "createdAt";
    public static final String ENTITY_TYPE_PROPERTY = "entityType";
    public static final String ID_PROPERTY = "id";
    public static final String MAIN_AUTHOR_PROPERTY = "mainAuthor";
    public static final String TITLE_PROPERTY = "title";
    public static final String UPDATED_AT_PROPERTY = "updatedAt";
    public static final String YEAR_PROPERTY = "year";
    public static final String FC_VALUE_ARRAY_PROPERTY = "fcValueArray";
    public static final String K0VALUE_ARRAY_PROPERTY = "k0ValueArray";
    public static final String KINF_VALUE_ARRAY_PROPERTY = "kinfValueArray";
    public static final String TO_BIBLIO_PROPERTY = "toBiblio";
    public static final String TO_BIBLIO1_PROPERTY = "toBiblio1";
    public static final String TO_BIBLIO2_PROPERTY = "toBiblio2";
    public static final String TO_CHANNEL_VALUE_PROPERTY = "toChannelValue";
    public static final String UNTITLED_REL_PROPERTY = "untitledRel";
    public static final String UNTITLED_REL1_PROPERTY = "untitledRel1";
    public static final String UNTITLED_REL2_PROPERTY = "untitledRel2";

    public static final String ID_PK_COLUMN = "id";

    public void setAuthors(String authors) {
        writeProperty("authors", authors);
    }
    public String getAuthors() {
        return (String)readProperty("authors");
    }

    public void setCreatedAt(Date createdAt) {
        writeProperty("createdAt", createdAt);
    }
    public Date getCreatedAt() {
        return (Date)readProperty("createdAt");
    }

    public void setEntityType(String entityType) {
        writeProperty("entityType", entityType);
    }
    public String getEntityType() {
        return (String)readProperty("entityType");
    }

    public void setId(Integer id) {
        writeProperty("id", id);
    }
    public Integer getId() {
        return (Integer)readProperty("id");
    }

    public void setMainAuthor(String mainAuthor) {
        writeProperty("mainAuthor", mainAuthor);
    }
    public String getMainAuthor() {
        return (String)readProperty("mainAuthor");
    }

    public void setTitle(String title) {
        writeProperty("title", title);
    }
    public String getTitle() {
        return (String)readProperty("title");
    }

    public void setUpdatedAt(Date updatedAt) {
        writeProperty("updatedAt", updatedAt);
    }
    public Date getUpdatedAt() {
        return (Date)readProperty("updatedAt");
    }

    public void setYear(Integer year) {
        writeProperty("year", year);
    }
    public Integer getYear() {
        return (Integer)readProperty("year");
    }

    public void addToFcValueArray(FcValue obj) {
        addToManyTarget("fcValueArray", obj, true);
    }
    public void removeFromFcValueArray(FcValue obj) {
        removeToManyTarget("fcValueArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<FcValue> getFcValueArray() {
        return (List<FcValue>)readProperty("fcValueArray");
    }


    public void addToK0ValueArray(K0Value obj) {
        addToManyTarget("k0ValueArray", obj, true);
    }
    public void removeFromK0ValueArray(K0Value obj) {
        removeToManyTarget("k0ValueArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<K0Value> getK0ValueArray() {
        return (List<K0Value>)readProperty("k0ValueArray");
    }


    public void addToKinfValueArray(KinfValue obj) {
        addToManyTarget("kinfValueArray", obj, true);
    }
    public void removeFromKinfValueArray(KinfValue obj) {
        removeToManyTarget("kinfValueArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<KinfValue> getKinfValueArray() {
        return (List<KinfValue>)readProperty("kinfValueArray");
    }


    public void setToBiblio(BiblioBook toBiblio) {
        setToOneTarget("toBiblio", toBiblio, true);
    }

    public BiblioBook getToBiblio() {
        return (BiblioBook)readProperty("toBiblio");
    }


    public void setToBiblio1(BiblioJournal toBiblio1) {
        setToOneTarget("toBiblio1", toBiblio1, true);
    }

    public BiblioJournal getToBiblio1() {
        return (BiblioJournal)readProperty("toBiblio1");
    }


    public void setToBiblio2(BiblioThesis toBiblio2) {
        setToOneTarget("toBiblio2", toBiblio2, true);
    }

    public BiblioThesis getToBiblio2() {
        return (BiblioThesis)readProperty("toBiblio2");
    }


    public void addToToChannelValue(ChannelValue obj) {
        addToManyTarget("toChannelValue", obj, true);
    }
    public void removeFromToChannelValue(ChannelValue obj) {
        removeToManyTarget("toChannelValue", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<ChannelValue> getToChannelValue() {
        return (List<ChannelValue>)readProperty("toChannelValue");
    }


    public void addToUntitledRel(ChannelValue obj) {
        addToManyTarget("untitledRel", obj, true);
    }
    public void removeFromUntitledRel(ChannelValue obj) {
        removeToManyTarget("untitledRel", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<ChannelValue> getUntitledRel() {
        return (List<ChannelValue>)readProperty("untitledRel");
    }


    public void addToUntitledRel1(ChannelValue obj) {
        addToManyTarget("untitledRel1", obj, true);
    }
    public void removeFromUntitledRel1(ChannelValue obj) {
        removeToManyTarget("untitledRel1", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<ChannelValue> getUntitledRel1() {
        return (List<ChannelValue>)readProperty("untitledRel1");
    }


    public void addToUntitledRel2(ChannelValue obj) {
        addToManyTarget("untitledRel2", obj, true);
    }
    public void removeFromUntitledRel2(ChannelValue obj) {
        removeToManyTarget("untitledRel2", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<ChannelValue> getUntitledRel2() {
        return (List<ChannelValue>)readProperty("untitledRel2");
    }


}
