package org.vamdc.kida.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.vamdc.kida.Biblio;

/**
 * Class _BiblioThesis was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _BiblioThesis extends CayenneDataObject {

    public static final String CREATED_AT_PROPERTY = "createdAt";
    public static final String MONTH_PROPERTY = "month";
    public static final String NUM_THESIS_PROPERTY = "numThesis";
    public static final String SCHOOL_PROPERTY = "school";
    public static final String UPDATED_AT_PROPERTY = "updatedAt";
    public static final String TO_BIBLIO_PROPERTY = "toBiblio";

    public static final String BIBLIOGRAPHY_ID_PK_COLUMN = "bibliography_id";

    public void setCreatedAt(Date createdAt) {
        writeProperty("createdAt", createdAt);
    }
    public Date getCreatedAt() {
        return (Date)readProperty("createdAt");
    }

    public void setMonth(String month) {
        writeProperty("month", month);
    }
    public String getMonth() {
        return (String)readProperty("month");
    }

    public void setNumThesis(String numThesis) {
        writeProperty("numThesis", numThesis);
    }
    public String getNumThesis() {
        return (String)readProperty("numThesis");
    }

    public void setSchool(String school) {
        writeProperty("school", school);
    }
    public String getSchool() {
        return (String)readProperty("school");
    }

    public void setUpdatedAt(Date updatedAt) {
        writeProperty("updatedAt", updatedAt);
    }
    public Date getUpdatedAt() {
        return (Date)readProperty("updatedAt");
    }

    public void setToBiblio(Biblio toBiblio) {
        setToOneTarget("toBiblio", toBiblio, true);
    }

    public Biblio getToBiblio() {
        return (Biblio)readProperty("toBiblio");
    }


}
