package org.vamdc.kida.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.vamdc.kida.BugsAndFeatures;

/**
 * Class _BugState was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _BugState extends CayenneDataObject {

    public static final String CREATED_AT_PROPERTY = "createdAt";
    public static final String NAME_PROPERTY = "name";
    public static final String ORDER_PROPERTY = "order";
    public static final String UPDATED_AT_PROPERTY = "updatedAt";
    public static final String BUGS_AND_FEATURES_ARRAY_PROPERTY = "bugsAndFeaturesArray";

    public static final String ID_PK_COLUMN = "id";

    public void setCreatedAt(Date createdAt) {
        writeProperty("createdAt", createdAt);
    }
    public Date getCreatedAt() {
        return (Date)readProperty("createdAt");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setOrder(Integer order) {
        writeProperty("order", order);
    }
    public Integer getOrder() {
        return (Integer)readProperty("order");
    }

    public void setUpdatedAt(Date updatedAt) {
        writeProperty("updatedAt", updatedAt);
    }
    public Date getUpdatedAt() {
        return (Date)readProperty("updatedAt");
    }

    public void addToBugsAndFeaturesArray(BugsAndFeatures obj) {
        addToManyTarget("bugsAndFeaturesArray", obj, true);
    }
    public void removeFromBugsAndFeaturesArray(BugsAndFeatures obj) {
        removeToManyTarget("bugsAndFeaturesArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<BugsAndFeatures> getBugsAndFeaturesArray() {
        return (List<BugsAndFeatures>)readProperty("bugsAndFeaturesArray");
    }


}
