package org.vamdc.kida.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.vamdc.kida.Channel;
import org.vamdc.kida.Specie;

/**
 * Class _ChannelHasSpecie was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ChannelHasSpecie extends CayenneDataObject {

    public static final String CREATED_AT_PROPERTY = "createdAt";
    public static final String OCCURRENCE_PROPERTY = "occurrence";
    public static final String TYPE_PROPERTY = "type";
    public static final String UPDATED_AT_PROPERTY = "updatedAt";
    public static final String SPECIE_REL_PROPERTY = "specieRel";
    public static final String TO_CHANNEL_PROPERTY = "toChannel";
    public static final String TO_SPECIE_PROPERTY = "toSpecie";

    public static final String CHANNEL_ID_PK_COLUMN = "channel_id";
    public static final String SPECIE_ID_PK_COLUMN = "specie_id";
    public static final String TYPE_PK_COLUMN = "type";

    public void setCreatedAt(Date createdAt) {
        writeProperty("createdAt", createdAt);
    }
    public Date getCreatedAt() {
        return (Date)readProperty("createdAt");
    }

    public void setOccurrence(Integer occurrence) {
        writeProperty("occurrence", occurrence);
    }
    public Integer getOccurrence() {
        return (Integer)readProperty("occurrence");
    }

    public void setType(String type) {
        writeProperty("type", type);
    }
    public String getType() {
        return (String)readProperty("type");
    }

    public void setUpdatedAt(Date updatedAt) {
        writeProperty("updatedAt", updatedAt);
    }
    public Date getUpdatedAt() {
        return (Date)readProperty("updatedAt");
    }

    public void setSpecieRel(Specie specieRel) {
        setToOneTarget("specieRel", specieRel, true);
    }

    public Specie getSpecieRel() {
        return (Specie)readProperty("specieRel");
    }


    public void setToChannel(Channel toChannel) {
        setToOneTarget("toChannel", toChannel, true);
    }

    public Channel getToChannel() {
        return (Channel)readProperty("toChannel");
    }


    public void setToSpecie(Specie toSpecie) {
        setToOneTarget("toSpecie", toSpecie, true);
    }

    public Specie getToSpecie() {
        return (Specie)readProperty("toSpecie");
    }


}
