package org.vamdc.kida.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.vamdc.kida.ChannelHasSpecie;
import org.vamdc.kida.ChannelValue;
import org.vamdc.kida.ExperimentHasChannel;
import org.vamdc.kida.Specie;
import org.vamdc.kida.TypeChannel;

/**
 * Class _Channel was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Channel extends CayenneDataObject {

    public static final String ADDED_STATUS_PROPERTY = "addedStatus";
    public static final String CREATED_AT_PROPERTY = "createdAt";
    public static final String NUM_PROPERTY = "num";
    public static final String STATUS_PROPERTY = "status";
    public static final String UPDATED_AT_PROPERTY = "updatedAt";
    public static final String CHANNEL_HAS_SPECIE_ARRAY_PROPERTY = "channelHasSpecieArray";
    public static final String CHANNEL_VALUE_ARRAY_PROPERTY = "channelValueArray";
    public static final String EXPERIMENT_HAS_CHANNEL_ARRAY_PROPERTY = "experimentHasChannelArray";
    public static final String SPECIE_REL_PROPERTY = "specieRel";
    public static final String TO_TYPE_CHANNEL_PROPERTY = "toTypeChannel";

    public static final String ID_PK_COLUMN = "id";

    public void setAddedStatus(Integer addedStatus) {
        writeProperty("addedStatus", addedStatus);
    }
    public Integer getAddedStatus() {
        return (Integer)readProperty("addedStatus");
    }

    public void setCreatedAt(Date createdAt) {
        writeProperty("createdAt", createdAt);
    }
    public Date getCreatedAt() {
        return (Date)readProperty("createdAt");
    }

    public void setNum(Integer num) {
        writeProperty("num", num);
    }
    public Integer getNum() {
        return (Integer)readProperty("num");
    }

    public void setStatus(String status) {
        writeProperty("status", status);
    }
    public String getStatus() {
        return (String)readProperty("status");
    }

    public void setUpdatedAt(Date updatedAt) {
        writeProperty("updatedAt", updatedAt);
    }
    public Date getUpdatedAt() {
        return (Date)readProperty("updatedAt");
    }

    public void addToChannelHasSpecieArray(ChannelHasSpecie obj) {
        addToManyTarget("channelHasSpecieArray", obj, true);
    }
    public void removeFromChannelHasSpecieArray(ChannelHasSpecie obj) {
        removeToManyTarget("channelHasSpecieArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<ChannelHasSpecie> getChannelHasSpecieArray() {
        return (List<ChannelHasSpecie>)readProperty("channelHasSpecieArray");
    }


    public void addToChannelValueArray(ChannelValue obj) {
        addToManyTarget("channelValueArray", obj, true);
    }
    public void removeFromChannelValueArray(ChannelValue obj) {
        removeToManyTarget("channelValueArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<ChannelValue> getChannelValueArray() {
        return (List<ChannelValue>)readProperty("channelValueArray");
    }


    public void addToExperimentHasChannelArray(ExperimentHasChannel obj) {
        addToManyTarget("experimentHasChannelArray", obj, true);
    }
    public void removeFromExperimentHasChannelArray(ExperimentHasChannel obj) {
        removeToManyTarget("experimentHasChannelArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<ExperimentHasChannel> getExperimentHasChannelArray() {
        return (List<ExperimentHasChannel>)readProperty("experimentHasChannelArray");
    }


    public void addToSpecieRel(Specie obj) {
        addToManyTarget("specieRel", obj, true);
    }
    public void removeFromSpecieRel(Specie obj) {
        removeToManyTarget("specieRel", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Specie> getSpecieRel() {
        return (List<Specie>)readProperty("specieRel");
    }


    public void setToTypeChannel(TypeChannel toTypeChannel) {
        setToOneTarget("toTypeChannel", toTypeChannel, true);
    }

    public TypeChannel getToTypeChannel() {
        return (TypeChannel)readProperty("toTypeChannel");
    }


}
