package org.vamdc.kida.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.vamdc.kida.Channel;
import org.vamdc.kida.Reaction;

/**
 * Class _ExperimentHasChannel was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ExperimentHasChannel extends CayenneDataObject {

    public static final String CREATED_AT_PROPERTY = "createdAt";
    public static final String UPDATED_AT_PROPERTY = "updatedAt";
    public static final String TO_CHANNEL_PROPERTY = "toChannel";
    public static final String TO_REACTION_PROPERTY = "toReaction";

    public static final String CHANNEL_ID_PK_COLUMN = "channel_id";
    public static final String REACTION_ID_PK_COLUMN = "reaction_id";

    public void setCreatedAt(Date createdAt) {
        writeProperty("createdAt", createdAt);
    }
    public Date getCreatedAt() {
        return (Date)readProperty("createdAt");
    }

    public void setUpdatedAt(Date updatedAt) {
        writeProperty("updatedAt", updatedAt);
    }
    public Date getUpdatedAt() {
        return (Date)readProperty("updatedAt");
    }

    public void setToChannel(Channel toChannel) {
        setToOneTarget("toChannel", toChannel, true);
    }

    public Channel getToChannel() {
        return (Channel)readProperty("toChannel");
    }


    public void setToReaction(Reaction toReaction) {
        setToOneTarget("toReaction", toReaction, true);
    }

    public Reaction getToReaction() {
        return (Reaction)readProperty("toReaction");
    }


}
