package org.vamdc.kida.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;

/**
 * Class _ExpertAdvice was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ExpertAdvice extends CayenneDataObject {

    public static final String ADVICE_PROPERTY = "advice";
    public static final String COMMENT_PROPERTY = "comment";
    public static final String CREATED_AT_PROPERTY = "createdAt";
    public static final String EXPERT_EMAIL_PROPERTY = "expertEmail";
    public static final String GROUP_ID_PROPERTY = "groupId";
    public static final String SUPER_EXPERT_EMAIL_PROPERTY = "superExpertEmail";
    public static final String UPDATED_AT_PROPERTY = "updatedAt";

    public static final String ID_PK_COLUMN = "id";

    public void setAdvice(String advice) {
        writeProperty("advice", advice);
    }
    public String getAdvice() {
        return (String)readProperty("advice");
    }

    public void setComment(String comment) {
        writeProperty("comment", comment);
    }
    public String getComment() {
        return (String)readProperty("comment");
    }

    public void setCreatedAt(Date createdAt) {
        writeProperty("createdAt", createdAt);
    }
    public Date getCreatedAt() {
        return (Date)readProperty("createdAt");
    }

    public void setExpertEmail(String expertEmail) {
        writeProperty("expertEmail", expertEmail);
    }
    public String getExpertEmail() {
        return (String)readProperty("expertEmail");
    }

    public void setGroupId(Integer groupId) {
        writeProperty("groupId", groupId);
    }
    public Integer getGroupId() {
        return (Integer)readProperty("groupId");
    }

    public void setSuperExpertEmail(String superExpertEmail) {
        writeProperty("superExpertEmail", superExpertEmail);
    }
    public String getSuperExpertEmail() {
        return (String)readProperty("superExpertEmail");
    }

    public void setUpdatedAt(Date updatedAt) {
        writeProperty("updatedAt", updatedAt);
    }
    public Date getUpdatedAt() {
        return (Date)readProperty("updatedAt");
    }

}
