package org.vamdc.kida.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.vamdc.kida.SfGuardUser;

/**
 * Class _GetLogged was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _GetLogged extends CayenneDataObject {

    public static final String CREATED_AT_PROPERTY = "createdAt";
    public static final String UPDATED_AT_PROPERTY = "updatedAt";
    public static final String TO_SF_GUARD_USER_PROPERTY = "toSfGuardUser";

    public static final String ID_PK_COLUMN = "id";

    public void setCreatedAt(Date createdAt) {
        writeProperty("createdAt", createdAt);
    }
    public Date getCreatedAt() {
        return (Date)readProperty("createdAt");
    }

    public void setUpdatedAt(Date updatedAt) {
        writeProperty("updatedAt", updatedAt);
    }
    public Date getUpdatedAt() {
        return (Date)readProperty("updatedAt");
    }

    public void setToSfGuardUser(SfGuardUser toSfGuardUser) {
        setToOneTarget("toSfGuardUser", toSfGuardUser, true);
    }

    public SfGuardUser getToSfGuardUser() {
        return (SfGuardUser)readProperty("toSfGuardUser");
    }


}
