package org.vamdc.kida.auto;

import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.vamdc.kida.SfGuardUser;

/**
 * Class _SfGuardRememberKey was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _SfGuardRememberKey extends CayenneDataObject {

    public static final String CREATED_AT_PROPERTY = "createdAt";
    public static final String REMEMBER_KEY_PROPERTY = "rememberKey";
    public static final String TO_SF_GUARD_USER_PROPERTY = "toSfGuardUser";

    public static final String IP_ADDRESS_PK_COLUMN = "ip_address";
    public static final String USER_ID_PK_COLUMN = "user_id";

    public void setCreatedAt(Date createdAt) {
        writeProperty("createdAt", createdAt);
    }
    public Date getCreatedAt() {
        return (Date)readProperty("createdAt");
    }

    public void setRememberKey(String rememberKey) {
        writeProperty("rememberKey", rememberKey);
    }
    public String getRememberKey() {
        return (String)readProperty("rememberKey");
    }

    public void setToSfGuardUser(SfGuardUser toSfGuardUser) {
        setToOneTarget("toSfGuardUser", toSfGuardUser, true);
    }

    public SfGuardUser getToSfGuardUser() {
        return (SfGuardUser)readProperty("toSfGuardUser");
    }


}
