package org.vamdc.kida.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.vamdc.kida.SfGuardGroupPermission;
import org.vamdc.kida.SfGuardUserPermission;

/**
 * Class _SfGuardPermission was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _SfGuardPermission extends CayenneDataObject {

    public static final String DESCRIPTION_PROPERTY = "description";
    public static final String NAME_PROPERTY = "name";
    public static final String SF_GUARD_GROUP_PERMISSION_ARRAY_PROPERTY = "sfGuardGroupPermissionArray";
    public static final String SF_GUARD_USER_PERMISSION_ARRAY_PROPERTY = "sfGuardUserPermissionArray";

    public static final String ID_PK_COLUMN = "id";

    public void setDescription(String description) {
        writeProperty("description", description);
    }
    public String getDescription() {
        return (String)readProperty("description");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void addToSfGuardGroupPermissionArray(SfGuardGroupPermission obj) {
        addToManyTarget("sfGuardGroupPermissionArray", obj, true);
    }
    public void removeFromSfGuardGroupPermissionArray(SfGuardGroupPermission obj) {
        removeToManyTarget("sfGuardGroupPermissionArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<SfGuardGroupPermission> getSfGuardGroupPermissionArray() {
        return (List<SfGuardGroupPermission>)readProperty("sfGuardGroupPermissionArray");
    }


    public void addToSfGuardUserPermissionArray(SfGuardUserPermission obj) {
        addToManyTarget("sfGuardUserPermissionArray", obj, true);
    }
    public void removeFromSfGuardUserPermissionArray(SfGuardUserPermission obj) {
        removeToManyTarget("sfGuardUserPermissionArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<SfGuardUserPermission> getSfGuardUserPermissionArray() {
        return (List<SfGuardUserPermission>)readProperty("sfGuardUserPermissionArray");
    }


}
