package org.vamdc.kida.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.vamdc.kida.BugsAndFeatures;
import org.vamdc.kida.ChannelValue;
import org.vamdc.kida.Comment;
import org.vamdc.kida.GetLogged;
import org.vamdc.kida.SfGuardRememberKey;
import org.vamdc.kida.SfGuardUserGroup;
import org.vamdc.kida.SfGuardUserPermission;
import org.vamdc.kida.SfGuardUserProfile;
import org.vamdc.kida.ThreeBodyChannelValue;
import org.vamdc.kida.TotalRate;

/**
 * Class _SfGuardUser was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _SfGuardUser extends CayenneDataObject {

    public static final String ALGORITHM_PROPERTY = "algorithm";
    public static final String CREATED_AT_PROPERTY = "createdAt";
    public static final String IS_ACTIVE_PROPERTY = "isActive";
    public static final String IS_SUPER_ADMIN_PROPERTY = "isSuperAdmin";
    public static final String LAST_LOGIN_PROPERTY = "lastLogin";
    public static final String PASSWORD_PROPERTY = "password";
    public static final String SALT_PROPERTY = "salt";
    public static final String BUGS_AND_FEATURES_ARRAY_PROPERTY = "bugsAndFeaturesArray";
    public static final String CHANNEL_VALUE_ARRAY_PROPERTY = "channelValueArray";
    public static final String CHANNEL_VALUE_ARRAY1_PROPERTY = "channelValueArray1";
    public static final String COMMENT_ARRAY_PROPERTY = "commentArray";
    public static final String GET_LOGGED_ARRAY_PROPERTY = "getLoggedArray";
    public static final String SF_GUARD_REMEMBER_KEY_ARRAY_PROPERTY = "sfGuardRememberKeyArray";
    public static final String SF_GUARD_USER_GROUP_ARRAY_PROPERTY = "sfGuardUserGroupArray";
    public static final String SF_GUARD_USER_PERMISSION_ARRAY_PROPERTY = "sfGuardUserPermissionArray";
    public static final String SF_GUARD_USER_PROFILE_ARRAY_PROPERTY = "sfGuardUserProfileArray";
    public static final String THREE_BODY_CHANNEL_VALUE_ARRAY_PROPERTY = "threeBodyChannelValueArray";
    public static final String THREE_BODY_CHANNEL_VALUE_ARRAY1_PROPERTY = "threeBodyChannelValueArray1";
    public static final String THREE_BODY_CHANNEL_VALUE_ARRAY2_PROPERTY = "threeBodyChannelValueArray2";
    public static final String TOTAL_RATE_ARRAY_PROPERTY = "totalRateArray";
    public static final String TOTAL_RATE_ARRAY1_PROPERTY = "totalRateArray1";

    public static final String ID_PK_COLUMN = "id";

    public void setAlgorithm(String algorithm) {
        writeProperty("algorithm", algorithm);
    }
    public String getAlgorithm() {
        return (String)readProperty("algorithm");
    }

    public void setCreatedAt(Date createdAt) {
        writeProperty("createdAt", createdAt);
    }
    public Date getCreatedAt() {
        return (Date)readProperty("createdAt");
    }

    public void setIsActive(Byte isActive) {
        writeProperty("isActive", isActive);
    }
    public Byte getIsActive() {
        return (Byte)readProperty("isActive");
    }

    public void setIsSuperAdmin(Byte isSuperAdmin) {
        writeProperty("isSuperAdmin", isSuperAdmin);
    }
    public Byte getIsSuperAdmin() {
        return (Byte)readProperty("isSuperAdmin");
    }

    public void setLastLogin(Date lastLogin) {
        writeProperty("lastLogin", lastLogin);
    }
    public Date getLastLogin() {
        return (Date)readProperty("lastLogin");
    }

    public void setPassword(String password) {
        writeProperty("password", password);
    }
    public String getPassword() {
        return (String)readProperty("password");
    }

    public void setSalt(String salt) {
        writeProperty("salt", salt);
    }
    public String getSalt() {
        return (String)readProperty("salt");
    }

    public void addToBugsAndFeaturesArray(BugsAndFeatures obj) {
        addToManyTarget("bugsAndFeaturesArray", obj, true);
    }
    public void removeFromBugsAndFeaturesArray(BugsAndFeatures obj) {
        removeToManyTarget("bugsAndFeaturesArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<BugsAndFeatures> getBugsAndFeaturesArray() {
        return (List<BugsAndFeatures>)readProperty("bugsAndFeaturesArray");
    }


    public void addToChannelValueArray(ChannelValue obj) {
        addToManyTarget("channelValueArray", obj, true);
    }
    public void removeFromChannelValueArray(ChannelValue obj) {
        removeToManyTarget("channelValueArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<ChannelValue> getChannelValueArray() {
        return (List<ChannelValue>)readProperty("channelValueArray");
    }


    public void addToChannelValueArray1(ChannelValue obj) {
        addToManyTarget("channelValueArray1", obj, true);
    }
    public void removeFromChannelValueArray1(ChannelValue obj) {
        removeToManyTarget("channelValueArray1", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<ChannelValue> getChannelValueArray1() {
        return (List<ChannelValue>)readProperty("channelValueArray1");
    }


    public void addToCommentArray(Comment obj) {
        addToManyTarget("commentArray", obj, true);
    }
    public void removeFromCommentArray(Comment obj) {
        removeToManyTarget("commentArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Comment> getCommentArray() {
        return (List<Comment>)readProperty("commentArray");
    }


    public void addToGetLoggedArray(GetLogged obj) {
        addToManyTarget("getLoggedArray", obj, true);
    }
    public void removeFromGetLoggedArray(GetLogged obj) {
        removeToManyTarget("getLoggedArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<GetLogged> getGetLoggedArray() {
        return (List<GetLogged>)readProperty("getLoggedArray");
    }


    public void addToSfGuardRememberKeyArray(SfGuardRememberKey obj) {
        addToManyTarget("sfGuardRememberKeyArray", obj, true);
    }
    public void removeFromSfGuardRememberKeyArray(SfGuardRememberKey obj) {
        removeToManyTarget("sfGuardRememberKeyArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<SfGuardRememberKey> getSfGuardRememberKeyArray() {
        return (List<SfGuardRememberKey>)readProperty("sfGuardRememberKeyArray");
    }


    public void addToSfGuardUserGroupArray(SfGuardUserGroup obj) {
        addToManyTarget("sfGuardUserGroupArray", obj, true);
    }
    public void removeFromSfGuardUserGroupArray(SfGuardUserGroup obj) {
        removeToManyTarget("sfGuardUserGroupArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<SfGuardUserGroup> getSfGuardUserGroupArray() {
        return (List<SfGuardUserGroup>)readProperty("sfGuardUserGroupArray");
    }


    public void addToSfGuardUserPermissionArray(SfGuardUserPermission obj) {
        addToManyTarget("sfGuardUserPermissionArray", obj, true);
    }
    public void removeFromSfGuardUserPermissionArray(SfGuardUserPermission obj) {
        removeToManyTarget("sfGuardUserPermissionArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<SfGuardUserPermission> getSfGuardUserPermissionArray() {
        return (List<SfGuardUserPermission>)readProperty("sfGuardUserPermissionArray");
    }


    public void addToSfGuardUserProfileArray(SfGuardUserProfile obj) {
        addToManyTarget("sfGuardUserProfileArray", obj, true);
    }
    public void removeFromSfGuardUserProfileArray(SfGuardUserProfile obj) {
        removeToManyTarget("sfGuardUserProfileArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<SfGuardUserProfile> getSfGuardUserProfileArray() {
        return (List<SfGuardUserProfile>)readProperty("sfGuardUserProfileArray");
    }


    public void addToThreeBodyChannelValueArray(ThreeBodyChannelValue obj) {
        addToManyTarget("threeBodyChannelValueArray", obj, true);
    }
    public void removeFromThreeBodyChannelValueArray(ThreeBodyChannelValue obj) {
        removeToManyTarget("threeBodyChannelValueArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<ThreeBodyChannelValue> getThreeBodyChannelValueArray() {
        return (List<ThreeBodyChannelValue>)readProperty("threeBodyChannelValueArray");
    }


    public void addToThreeBodyChannelValueArray1(ThreeBodyChannelValue obj) {
        addToManyTarget("threeBodyChannelValueArray1", obj, true);
    }
    public void removeFromThreeBodyChannelValueArray1(ThreeBodyChannelValue obj) {
        removeToManyTarget("threeBodyChannelValueArray1", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<ThreeBodyChannelValue> getThreeBodyChannelValueArray1() {
        return (List<ThreeBodyChannelValue>)readProperty("threeBodyChannelValueArray1");
    }


    public void addToThreeBodyChannelValueArray2(ThreeBodyChannelValue obj) {
        addToManyTarget("threeBodyChannelValueArray2", obj, true);
    }
    public void removeFromThreeBodyChannelValueArray2(ThreeBodyChannelValue obj) {
        removeToManyTarget("threeBodyChannelValueArray2", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<ThreeBodyChannelValue> getThreeBodyChannelValueArray2() {
        return (List<ThreeBodyChannelValue>)readProperty("threeBodyChannelValueArray2");
    }


    public void addToTotalRateArray(TotalRate obj) {
        addToManyTarget("totalRateArray", obj, true);
    }
    public void removeFromTotalRateArray(TotalRate obj) {
        removeToManyTarget("totalRateArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<TotalRate> getTotalRateArray() {
        return (List<TotalRate>)readProperty("totalRateArray");
    }


    public void addToTotalRateArray1(TotalRate obj) {
        addToManyTarget("totalRateArray1", obj, true);
    }
    public void removeFromTotalRateArray1(TotalRate obj) {
        removeToManyTarget("totalRateArray1", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<TotalRate> getTotalRateArray1() {
        return (List<TotalRate>)readProperty("totalRateArray1");
    }


}
