package org.vamdc.kida.auto;

import org.apache.cayenne.CayenneDataObject;
import org.vamdc.kida.SfGuardGroup;
import org.vamdc.kida.SfGuardPermission;

/**
 * Class _SfGuardGroupPermission was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _SfGuardGroupPermission extends CayenneDataObject {

    public static final String TO_SF_GUARD_GROUP_PROPERTY = "toSfGuardGroup";
    public static final String TO_SF_GUARD_PERMISSION_PROPERTY = "toSfGuardPermission";

    public static final String GROUP_ID_PK_COLUMN = "group_id";
    public static final String PERMISSION_ID_PK_COLUMN = "permission_id";

    public void setToSfGuardGroup(SfGuardGroup toSfGuardGroup) {
        setToOneTarget("toSfGuardGroup", toSfGuardGroup, true);
    }

    public SfGuardGroup getToSfGuardGroup() {
        return (SfGuardGroup)readProperty("toSfGuardGroup");
    }


    public void setToSfGuardPermission(SfGuardPermission toSfGuardPermission) {
        setToOneTarget("toSfGuardPermission", toSfGuardPermission, true);
    }

    public SfGuardPermission getToSfGuardPermission() {
        return (SfGuardPermission)readProperty("toSfGuardPermission");
    }


}
