package org.vamdc.kida.auto;

import org.apache.cayenne.CayenneDataObject;
import org.vamdc.kida.SfGuardGroup;
import org.vamdc.kida.SfGuardUser;

/**
 * Class _SfGuardUserGroup was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _SfGuardUserGroup extends CayenneDataObject {

    public static final String TO_SF_GUARD_GROUP_PROPERTY = "toSfGuardGroup";
    public static final String TO_SF_GUARD_USER_PROPERTY = "toSfGuardUser";

    public static final String GROUP_ID_PK_COLUMN = "group_id";
    public static final String USER_ID_PK_COLUMN = "user_id";

    public void setToSfGuardGroup(SfGuardGroup toSfGuardGroup) {
        setToOneTarget("toSfGuardGroup", toSfGuardGroup, true);
    }

    public SfGuardGroup getToSfGuardGroup() {
        return (SfGuardGroup)readProperty("toSfGuardGroup");
    }


    public void setToSfGuardUser(SfGuardUser toSfGuardUser) {
        setToOneTarget("toSfGuardUser", toSfGuardUser, true);
    }

    public SfGuardUser getToSfGuardUser() {
        return (SfGuardUser)readProperty("toSfGuardUser");
    }


}
