package org.vamdc.kida.auto;

import org.apache.cayenne.CayenneDataObject;
import org.vamdc.kida.SfGuardPermission;
import org.vamdc.kida.SfGuardUser;

/**
 * Class _SfGuardUserPermission was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _SfGuardUserPermission extends CayenneDataObject {

    public static final String TO_SF_GUARD_PERMISSION_PROPERTY = "toSfGuardPermission";
    public static final String TO_SF_GUARD_USER_PROPERTY = "toSfGuardUser";

    public static final String PERMISSION_ID_PK_COLUMN = "permission_id";
    public static final String USER_ID_PK_COLUMN = "user_id";

    public void setToSfGuardPermission(SfGuardPermission toSfGuardPermission) {
        setToOneTarget("toSfGuardPermission", toSfGuardPermission, true);
    }

    public SfGuardPermission getToSfGuardPermission() {
        return (SfGuardPermission)readProperty("toSfGuardPermission");
    }


    public void setToSfGuardUser(SfGuardUser toSfGuardUser) {
        setToOneTarget("toSfGuardUser", toSfGuardUser, true);
    }

    public SfGuardUser getToSfGuardUser() {
        return (SfGuardUser)readProperty("toSfGuardUser");
    }


}
