package org.vamdc.kida.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.vamdc.kida.ThreeBodyReactionHasChannel;

/**
 * Class _ThreeBodyReaction was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ThreeBodyReaction extends CayenneDataObject {

    public static final String CREATED_AT_PROPERTY = "createdAt";
    public static final String UPDATED_AT_PROPERTY = "updatedAt";
    public static final String THREE_BODY_REACTION_HAS_CHANNEL_ARRAY_PROPERTY = "threeBodyReactionHasChannelArray";

    public static final String ID_PK_COLUMN = "id";

    public void setCreatedAt(Date createdAt) {
        writeProperty("createdAt", createdAt);
    }
    public Date getCreatedAt() {
        return (Date)readProperty("createdAt");
    }

    public void setUpdatedAt(Date updatedAt) {
        writeProperty("updatedAt", updatedAt);
    }
    public Date getUpdatedAt() {
        return (Date)readProperty("updatedAt");
    }

    public void addToThreeBodyReactionHasChannelArray(ThreeBodyReactionHasChannel obj) {
        addToManyTarget("threeBodyReactionHasChannelArray", obj, true);
    }
    public void removeFromThreeBodyReactionHasChannelArray(ThreeBodyReactionHasChannel obj) {
        removeToManyTarget("threeBodyReactionHasChannelArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<ThreeBodyReactionHasChannel> getThreeBodyReactionHasChannelArray() {
        return (List<ThreeBodyReactionHasChannel>)readProperty("threeBodyReactionHasChannelArray");
    }


}
