package org.vamdc.kida.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.vamdc.kida.ThreeBodyChannelHasSpecie;
import org.vamdc.kida.ThreeBodyChannelValue;
import org.vamdc.kida.ThreeBodyReactionHasChannel;
import org.vamdc.kida.ThreeBodyReactionHasReactant;

/**
 * Class _ThreeBodyChannel was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ThreeBodyChannel extends CayenneDataObject {

    public static final String CREATED_AT_PROPERTY = "createdAt";
    public static final String STATUS_PROPERTY = "status";
    public static final String UPDATED_AT_PROPERTY = "updatedAt";
    public static final String THREE_BODY_CHANNEL_HAS_SPECIE_ARRAY_PROPERTY = "threeBodyChannelHasSpecieArray";
    public static final String THREE_BODY_CHANNEL_VALUE_ARRAY_PROPERTY = "threeBodyChannelValueArray";
    public static final String THREE_BODY_REACTION_HAS_CHANNEL_ARRAY_PROPERTY = "threeBodyReactionHasChannelArray";
    public static final String THREE_BODY_REACTION_HAS_REACTANT_ARRAY_PROPERTY = "threeBodyReactionHasReactantArray";

    public static final String ID_PK_COLUMN = "id";

    public void setCreatedAt(Date createdAt) {
        writeProperty("createdAt", createdAt);
    }
    public Date getCreatedAt() {
        return (Date)readProperty("createdAt");
    }

    public void setStatus(String status) {
        writeProperty("status", status);
    }
    public String getStatus() {
        return (String)readProperty("status");
    }

    public void setUpdatedAt(Date updatedAt) {
        writeProperty("updatedAt", updatedAt);
    }
    public Date getUpdatedAt() {
        return (Date)readProperty("updatedAt");
    }

    public void addToThreeBodyChannelHasSpecieArray(ThreeBodyChannelHasSpecie obj) {
        addToManyTarget("threeBodyChannelHasSpecieArray", obj, true);
    }
    public void removeFromThreeBodyChannelHasSpecieArray(ThreeBodyChannelHasSpecie obj) {
        removeToManyTarget("threeBodyChannelHasSpecieArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<ThreeBodyChannelHasSpecie> getThreeBodyChannelHasSpecieArray() {
        return (List<ThreeBodyChannelHasSpecie>)readProperty("threeBodyChannelHasSpecieArray");
    }


    public void addToThreeBodyChannelValueArray(ThreeBodyChannelValue obj) {
        addToManyTarget("threeBodyChannelValueArray", obj, true);
    }
    public void removeFromThreeBodyChannelValueArray(ThreeBodyChannelValue obj) {
        removeToManyTarget("threeBodyChannelValueArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<ThreeBodyChannelValue> getThreeBodyChannelValueArray() {
        return (List<ThreeBodyChannelValue>)readProperty("threeBodyChannelValueArray");
    }


    public void addToThreeBodyReactionHasChannelArray(ThreeBodyReactionHasChannel obj) {
        addToManyTarget("threeBodyReactionHasChannelArray", obj, true);
    }
    public void removeFromThreeBodyReactionHasChannelArray(ThreeBodyReactionHasChannel obj) {
        removeToManyTarget("threeBodyReactionHasChannelArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<ThreeBodyReactionHasChannel> getThreeBodyReactionHasChannelArray() {
        return (List<ThreeBodyReactionHasChannel>)readProperty("threeBodyReactionHasChannelArray");
    }


    public void addToThreeBodyReactionHasReactantArray(ThreeBodyReactionHasReactant obj) {
        addToManyTarget("threeBodyReactionHasReactantArray", obj, true);
    }
    public void removeFromThreeBodyReactionHasReactantArray(ThreeBodyReactionHasReactant obj) {
        removeToManyTarget("threeBodyReactionHasReactantArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<ThreeBodyReactionHasReactant> getThreeBodyReactionHasReactantArray() {
        return (List<ThreeBodyReactionHasReactant>)readProperty("threeBodyReactionHasReactantArray");
    }


}
