package org.vamdc.kida.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.vamdc.kida.FcValue;
import org.vamdc.kida.Formula;
import org.vamdc.kida.K0Value;
import org.vamdc.kida.KinfValue;
import org.vamdc.kida.SfGuardUser;
import org.vamdc.kida.ThreeBodyChannel;
import org.vamdc.kida.ValidityRange;

/**
 * Class _ThreeBodyChannelValue was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ThreeBodyChannelValue extends CayenneDataObject {

    public static final String APPLICATION_PROPERTY = "application";
    public static final String CREATED_AT_PROPERTY = "createdAt";
    public static final String DESCRIPTION_PROPERTY = "description";
    public static final String EXPERTIZE_PROPERTY = "expertize";
    public static final String IS_TRASH_PROPERTY = "isTrash";
    public static final String JUSTIFICATION_PROPERTY = "justification";
    public static final String STATUS_PROPERTY = "status";
    public static final String TRASH_COMMENT_PROPERTY = "trashComment";
    public static final String UPDATED_AT_PROPERTY = "updatedAt";
    public static final String FC_VALUE_ARRAY_PROPERTY = "fcValueArray";
    public static final String K0VALUE_ARRAY_PROPERTY = "k0ValueArray";
    public static final String KINF_VALUE_ARRAY_PROPERTY = "kinfValueArray";
    public static final String TO_FORMULA_PROPERTY = "toFormula";
    public static final String TO_SF_GUARD_USER_PROPERTY = "toSfGuardUser";
    public static final String TO_SF_GUARD_USER1_PROPERTY = "toSfGuardUser1";
    public static final String TO_SF_GUARD_USER2_PROPERTY = "toSfGuardUser2";
    public static final String TO_THREE_BODY_CHANNEL_PROPERTY = "toThreeBodyChannel";
    public static final String TO_VALIDITY_RANGE_PROPERTY = "toValidityRange";

    public static final String ID_PK_COLUMN = "id";

    public void setApplication(String application) {
        writeProperty("application", application);
    }
    public String getApplication() {
        return (String)readProperty("application");
    }

    public void setCreatedAt(Date createdAt) {
        writeProperty("createdAt", createdAt);
    }
    public Date getCreatedAt() {
        return (Date)readProperty("createdAt");
    }

    public void setDescription(String description) {
        writeProperty("description", description);
    }
    public String getDescription() {
        return (String)readProperty("description");
    }

    public void setExpertize(Integer expertize) {
        writeProperty("expertize", expertize);
    }
    public Integer getExpertize() {
        return (Integer)readProperty("expertize");
    }

    public void setIsTrash(Integer isTrash) {
        writeProperty("isTrash", isTrash);
    }
    public Integer getIsTrash() {
        return (Integer)readProperty("isTrash");
    }

    public void setJustification(String justification) {
        writeProperty("justification", justification);
    }
    public String getJustification() {
        return (String)readProperty("justification");
    }

    public void setStatus(Integer status) {
        writeProperty("status", status);
    }
    public Integer getStatus() {
        return (Integer)readProperty("status");
    }

    public void setTrashComment(String trashComment) {
        writeProperty("trashComment", trashComment);
    }
    public String getTrashComment() {
        return (String)readProperty("trashComment");
    }

    public void setUpdatedAt(Date updatedAt) {
        writeProperty("updatedAt", updatedAt);
    }
    public Date getUpdatedAt() {
        return (Date)readProperty("updatedAt");
    }

    public void addToFcValueArray(FcValue obj) {
        addToManyTarget("fcValueArray", obj, true);
    }
    public void removeFromFcValueArray(FcValue obj) {
        removeToManyTarget("fcValueArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<FcValue> getFcValueArray() {
        return (List<FcValue>)readProperty("fcValueArray");
    }


    public void addToK0ValueArray(K0Value obj) {
        addToManyTarget("k0ValueArray", obj, true);
    }
    public void removeFromK0ValueArray(K0Value obj) {
        removeToManyTarget("k0ValueArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<K0Value> getK0ValueArray() {
        return (List<K0Value>)readProperty("k0ValueArray");
    }


    public void addToKinfValueArray(KinfValue obj) {
        addToManyTarget("kinfValueArray", obj, true);
    }
    public void removeFromKinfValueArray(KinfValue obj) {
        removeToManyTarget("kinfValueArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<KinfValue> getKinfValueArray() {
        return (List<KinfValue>)readProperty("kinfValueArray");
    }


    public void setToFormula(Formula toFormula) {
        setToOneTarget("toFormula", toFormula, true);
    }

    public Formula getToFormula() {
        return (Formula)readProperty("toFormula");
    }


    public void setToSfGuardUser(SfGuardUser toSfGuardUser) {
        setToOneTarget("toSfGuardUser", toSfGuardUser, true);
    }

    public SfGuardUser getToSfGuardUser() {
        return (SfGuardUser)readProperty("toSfGuardUser");
    }


    public void setToSfGuardUser1(SfGuardUser toSfGuardUser1) {
        setToOneTarget("toSfGuardUser1", toSfGuardUser1, true);
    }

    public SfGuardUser getToSfGuardUser1() {
        return (SfGuardUser)readProperty("toSfGuardUser1");
    }


    public void setToSfGuardUser2(SfGuardUser toSfGuardUser2) {
        setToOneTarget("toSfGuardUser2", toSfGuardUser2, true);
    }

    public SfGuardUser getToSfGuardUser2() {
        return (SfGuardUser)readProperty("toSfGuardUser2");
    }


    public void setToThreeBodyChannel(ThreeBodyChannel toThreeBodyChannel) {
        setToOneTarget("toThreeBodyChannel", toThreeBodyChannel, true);
    }

    public ThreeBodyChannel getToThreeBodyChannel() {
        return (ThreeBodyChannel)readProperty("toThreeBodyChannel");
    }


    public void setToValidityRange(ValidityRange toValidityRange) {
        setToOneTarget("toValidityRange", toValidityRange, true);
    }

    public ValidityRange getToValidityRange() {
        return (ValidityRange)readProperty("toValidityRange");
    }


}
