package org.vamdc.kida.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.vamdc.kida.ChannelValue;
import org.vamdc.kida.ThreeBodyChannelValue;
import org.vamdc.kida.TotalRate;

/**
 * Class _ValidityRange was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ValidityRange extends CayenneDataObject {

    public static final String CREATED_AT_PROPERTY = "createdAt";
    public static final String PMAX_PROPERTY = "pmax";
    public static final String PMIN_PROPERTY = "pmin";
    public static final String TMAX_PROPERTY = "tmax";
    public static final String TMIN_PROPERTY = "tmin";
    public static final String UPDATED_AT_PROPERTY = "updatedAt";
    public static final String CHANNEL_VALUE_ARRAY_PROPERTY = "channelValueArray";
    public static final String THREE_BODY_CHANNEL_VALUE_ARRAY_PROPERTY = "threeBodyChannelValueArray";
    public static final String TOTAL_RATE_ARRAY_PROPERTY = "totalRateArray";

    public static final String ID_PK_COLUMN = "id";

    public void setCreatedAt(Date createdAt) {
        writeProperty("createdAt", createdAt);
    }
    public Date getCreatedAt() {
        return (Date)readProperty("createdAt");
    }

    public void setPmax(Integer pmax) {
        writeProperty("pmax", pmax);
    }
    public Integer getPmax() {
        return (Integer)readProperty("pmax");
    }

    public void setPmin(Integer pmin) {
        writeProperty("pmin", pmin);
    }
    public Integer getPmin() {
        return (Integer)readProperty("pmin");
    }

    public void setTmax(Integer tmax) {
        writeProperty("tmax", tmax);
    }
    public Integer getTmax() {
        return (Integer)readProperty("tmax");
    }

    public void setTmin(Integer tmin) {
        writeProperty("tmin", tmin);
    }
    public Integer getTmin() {
        return (Integer)readProperty("tmin");
    }

    public void setUpdatedAt(Date updatedAt) {
        writeProperty("updatedAt", updatedAt);
    }
    public Date getUpdatedAt() {
        return (Date)readProperty("updatedAt");
    }

    public void addToChannelValueArray(ChannelValue obj) {
        addToManyTarget("channelValueArray", obj, true);
    }
    public void removeFromChannelValueArray(ChannelValue obj) {
        removeToManyTarget("channelValueArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<ChannelValue> getChannelValueArray() {
        return (List<ChannelValue>)readProperty("channelValueArray");
    }


    public void addToThreeBodyChannelValueArray(ThreeBodyChannelValue obj) {
        addToManyTarget("threeBodyChannelValueArray", obj, true);
    }
    public void removeFromThreeBodyChannelValueArray(ThreeBodyChannelValue obj) {
        removeToManyTarget("threeBodyChannelValueArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<ThreeBodyChannelValue> getThreeBodyChannelValueArray() {
        return (List<ThreeBodyChannelValue>)readProperty("threeBodyChannelValueArray");
    }


    public void addToTotalRateArray(TotalRate obj) {
        addToManyTarget("totalRateArray", obj, true);
    }
    public void removeFromTotalRateArray(TotalRate obj) {
        removeToManyTarget("totalRateArray", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<TotalRate> getTotalRateArray() {
        return (List<TotalRate>)readProperty("totalRateArray");
    }


}
